src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityMilestones__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity Milestone</label>
    <nameField>
        <displayFormat>AM-{000000000}</displayFormat>
        <label>ActivityMilestones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivitySkills__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skills__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Activity Skill</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Activity Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Place__c</fullName>
        <label>Place</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Award</label>
    <nameField>
        <displayFormat>Award-{000000000}</displayFormat>
        <label>Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <label>Registration Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Submission__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitting_Member__c</fullName>
        <label>Submitting Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <label>Registration Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Requirement_Weight__c</fullName>
        <description>Importance of a particular requirement</description>
        <inlineHelpText>Importance of a particular requirement</inlineHelpText>
        <label>Requirement Weight</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Application Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Offering__c</fullName>
        <label>Service Offering</label>
        <picklist>
            <picklistValues>
                <fullName>Analytics and Data Management Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Process Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Center, Workload and Cloud Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Security Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility and Workplace Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitting_Member__c</fullName>
        <label>Submitting Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Crowd_Exchange_Organization__c</fullName>
        <label>Crowd Exchange Organization</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Crowd_Exchange_User_Type__c</fullName>
        <label>Crowd_Exchange_User_Type</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publisher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/UserSkill__c.object
<CustomObject>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skills__c</referenceTo>
        <relationshipLabel>User Skills</relationshipLabel>
        <relationshipName>User_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Skill</label>
    <nameField>
        <displayFormat>US-{000000000}</displayFormat>
        <label>UserSkill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WebAppModels.cls
public with sharing abstract class WebAppModels {
    /**
     * DTO model for fetching stories list
     */
    public class StoryRequest{
        public Integer page { get; set; }
        public Integer pageSize { get; set; }
        public StoryFilter filter { get; set; }
        
    }
    /**
     * Stories filter object for the StoryRequest
     */
    public class StoryFilter{
        public String storyTitle { get; set; }
        public String activityTitle { get; set; }
        public String serviceOffering { get; set; }
        public String activityPhase { get; set; }
        public Boolean showOnlyCompleted { get; set; }

        public Boolean hasAnyFilter(){
            return storyTitle!=null||activityTitle!=null||serviceOffering!=null||activityPhase!=null||showOnlyCompleted;
        }
    }
    /**
     * Stories list response
     */
    public class StoryResponse{
        public List<Story> stories { get; set; }
        public Integer totalItems { get; set; }
        public Integer totalPages { get; set; }
    }
    /**
     * DTO object for the Story__c object
     */
    public class Story {
        public Id id { get; set; }
        public String title { get; set; }
        public String description { get; set; }
        public String phase { get; set; }
        public String serviceOffering { get; set; }
        public List<Activity> activities { get; set; }
        public UserModel publisher { get; set; }
        public Story(){}
        public Story(Story__c model){
            try{
                this.id = model.Id;
                this.serviceOffering = model.Service_Offering__c;
                this.title = model.Name;
                this.description = model.Description__c;
                this.phase = model.Status__c;
                this.activities = new List<Activity>();
                this.publisher = new UserModel(model.Publisher__r);
            }catch(Exception ex){
                //Just for Activity as a root case       
            }
        }
    }
    /**
     * DTO model for the Skills objects
     */
    public class CodeType{
        public Id id { get; set; } 
        public String name { get; set; }
        public String skillId { get; set; }
        public CodeType(ActivitySkills__c model){
            this.id = model.id;
            this.name = model.Skill__r.Name;
            this.skillId = model.Skill__c;
        }
        public CodeType(Skills__c model){
            this.skillId = model.id;
            this.name = model.Name;
        }
        public CodeType(UserSkill__c model){
            this.id = model.id;
            this.name = model.Skill__r.Name;
            this.skillId = model.Skill__c;
        }
    }
    /**
     * DTO model for the standard milestones
     */
    public virtual class MilestoneInfo implements Comparable{
        public String name {get;set;}
        public Integer defaultDuration {get;set;}
        public Integer stepNumber {get;set;}
        public Boolean display {get;set;}

        public MilestoneInfo(Milestone__c model){
            this.name = model.Name;
            this.display = model.Display_In_Initial_Setup__c;
            if(model.Default_Time_Period__c!=null)
                this.defaultDuration = model.Default_Time_Period__c.intValue();
            this.stepNumber = model.Step_Number__c.intValue();
        }
        // Compare opportunities based on the opportunity amount.
        public Integer compareTo(Object compareTo) {
            // Cast argument to MilestoneInfo
            MilestoneInfo compareToMilestone = (MilestoneInfo)compareTo;
            
            // The return value of 0 indicates that both elements are equal.
            Integer returnValue = 0;
            if (this.stepNumber > compareToMilestone.stepNumber) {
                // Set return value to a positive value.
                returnValue = 1;
            } else if (this.stepNumber < compareToMilestone.stepNumber) {
                // Set return value to a negative value.
                returnValue = -1;
            }
            
            return returnValue;       
        }
    }
    /**
     * DTO model for the Activity's milestone object
     */
    public class ActivityMilestone extends MilestoneInfo{
        public Date scheduledDate { get; set; } 
        public Date completedDate { get; set; } 
        public Id milestoneId { get; set; }
        public ActivityMilestone(ActivityMilestones__c model){
            super(model.Milestone__r);
            this.scheduledDate = model.Scheduled_Date__c;
            this.completedDate = model.Completed_Date__c;
            this.name = model.Milestone__r.Name;
        }
        public ActivityMilestones__c getSObject(){
            return new ActivityMilestones__c(
                Scheduled_Date__c = this.scheduledDate
                );
        }

    }
    /**
     * DTO model for the Activity's Requirement object
     */
    public class ActivityRequirement {
        public Id id { get; set; }
        public List<ActivityRequirement> childRequirements { get; set; }
        public String requirementNumber { get; set; }
        public String importance { get; set; }
        public String description { get; set; }
        public String type { get; set; }
        public ActivityRequirement(Requirement__c model){
            this.id = model.Id;
            this.requirementNumber = model.Requirement_Number__c;
            this.importance = model.Requirement_Weight__c;
            this.description = model.Description__c;
            this.type = model.Type__c;
            this.childRequirements = new List<ActivityRequirement>();
        }
        public Requirement__c getSObject(){
            return new Requirement__c(
                Id = this.id,
                Requirement_Number__c = this.requirementNumber,
                Requirement_Weight__c = this.importance ,
                Description__c = this.description ,
                Type__c = this.type 
                );
        }
    }
    /**
     * DTO model for the User object
     */
    public class UserModel{
        public Id id { get; set; }
        public String firstName { get; set; }
        public String lastName { get; set; }
        public String photoUrl { get; set; }
        public String role { get; set; }
        public String organization { get; set; }
        public Integer activitiesDone { get; set; }
        public List<CodeType> skills { get; set; }
        public UserModel(User model){
            this.id = model.Id;
            this.firstName = model.FirstName;
            this.lastName = model.LastName;
            this.photoUrl = model.SmallPhotoUrl;
            try{
                this.activitiesDone = model.Submissions__r.size();
            } catch(Exception ex){}
            try{
                this.role = model.Crowd_Exchange_User_Type__c;
            } catch(Exception ex){}
            try{
                this.organization = model.Crowd_Exchange_Organization__c ;
            } catch(Exception ex){}
        }
        public void addSkills(List<UserSkill__c> skills){
            if(this.skills == null)
                this.skills = new List<CodeType>();
            for(UserSkill__c skill : skills){
                this.skills.add(new CodeType(skill));
            }
        }
    }
    /**
     * DTO model for the Registration__c object
     */
    public class ActivityRegitration{
        public Id id { get; set; }
        public DateTime registrationDate { get; set; }
        public UserModel user { get; set; } 

        public ActivityRegitration(Registration__c model){
            this.id = model.Id;
            this.registrationDate = model.Registration_Date__c;
            try{
                this.user = new UserModel(model.User__r);
            } catch(Exception ex){}
        }
    }
    /**
     * DTO model for the Submission__c object
     */
    public class ActivitySubmission{
        public Id id { get; set; }
        public DateTime submissionDate { get; set; }
        public UserModel user { get; set; } 

        public ActivitySubmission(Submission__c model){

        }
    }
    /**
     * DTO model for the Award__c object
     */
    public class Prize{
        public Id id { get; set; }
        public Integer place { get; set; }
        public Decimal amount { get; set; }
        public Prize(Award__c award){
            this.id = award.Id;
            this.place = award.Place__c.intValue();
            this.amount = award.Payment__c;
        }
    }
    /**
     * DTO model for the Activity's attachment
     */
    public class ActivityDocument{
        public Id id { get; set; }
        public String name { get; set; } 
        public String description { get; set; }
        public Datetime createdDate { get; set; }

        public ActivityDocument(Attachment att){
            this.id = att.Id;
            this.name = att.Name;
            this.description = att.Description;
            this.createdDate = att.CreatedDate;
        }
    }
    /**
     * DTO model for the Activity__c object
     */
    public class Activity{
        public Id id { get; set; }
        public String title { get; set; }
        public String description { get; set; }
        public String phase { get; set; }
        public Boolean isRegistered { get; set; }
        public List<CodeType> codeTypes { get; set; }
        public String challengeType { get; set; }
        public List<ActivityRequirement> requirements { get; set; }
        public List<ActivityMilestone> milestones { get; set; }
        public List<ActivityRegitration> registrations { get; set; }
        public List<ActivitySubmission> submissions { get; set; }
        public Integer registrationsCount { get; set; }
        public Integer submissionsCount { get; set; }
        public List<ActivityDocument> documents { get; set; }
        public List<Prize> prizes { get; set; }
        public Id storyId { get; set; }
        public Story story { get; set; }
        public Boolean noPrizes { get; set; }
        public UserModel assignedMember { get;set; }
        public Activity(Activity__c model){
            this.id = model.Id;
            this.title = model.Name;
            this.description = model.Description__c;
            this.codeTypes = new List<CodeType>();
            this.phase = model.Status__c;
            this.isRegistered = false;
            this.challengeType = model.Challenge_Type__c;
            this.story = new Story(model.Story__r);
            if(model.Assigned_Member__c!=null)
                this.assignedMember = new UserModel(model.Assigned_Member__r);
            this.noPrizes = model.hasAwards__c==null?false:!model.hasAwards__c;
            for(ActivitySkills__c skill : model.Activity_Skills__r){
                this.codeTypes.add(new CodeType(skill));
            }
            this.milestones = new List<ActivityMilestone>();
            for(ActivityMilestones__c milestone : model.ActivityMilestones__r){
                this.milestones.add(new ActivityMilestone(milestone));
            }
            this.milestones.sort();
            this.requirements = new List<ActivityRequirement>();
            Map<Id, ActivityRequirement> requirementsMap = new Map<Id, ActivityRequirement>();
            List<Requirement__c> childRequirements = new List<Requirement__c>();
            for(Requirement__c requirement : model.Requirements__r){
                if(requirement.Parent_Requirement__c!=null){
                    childRequirements.add(requirement);
                } else {
                    ActivityRequirement requirementDto = new ActivityRequirement(requirement);
                    this.requirements.add(requirementDto);
                    requirementsMap.put(requirement.Id, requirementDto);
                }
            }
            for(Requirement__c requirement : childRequirements){
                requirementsMap.get(requirement.Parent_Requirement__c).childRequirements.add(new ActivityRequirement(requirement));
            }
            this.prizes = new List<Prize>();
            for(Award__c award : model.Awards__r)
                this.prizes.add(new Prize(award));

            this.registrations = new List<ActivityRegitration>();
            this.registrationsCount = model.Registrations__r.size();
            String userId = UserInfo.getUserId();
            for(Registration__c reg : model.Registrations__r){
                //ActivityRegitration regDto = new ActivityRegitration(reg);
                //this.registrations.add(regDto); //too hight payload. used separate fetch
                if(reg.User__r.Id==userId)
                    this.isRegistered = true;
            }
            this.submissions = new List<ActivitySubmission>();
            this.submissionsCount = model.Submissions__r.size();
            //too hight payload. create and use separate fetch
            //for(Submission__c submission : model.Submissions__r){
            //    this.submissions.add(new ActivitySubmission(submission));
            //}
            this.documents = new List<ActivityDocument>();
            for(Attachment att : model.Attachments){
                this.documents.add(new ActivityDocument(att));
            }
        }
        public Activity__c getSObject(){
            Activity__c result = new Activity__c(
                Id = this.id,
                Name = this.title,
                Description__c = this.description,
                Status__c = this.phase,
                Challenge_Type__c = this.challengeType,
                hasAwards__c = this.noPrizes==null?false:!this.noPrizes
                );
            if(String.isNotBlank(this.storyId))
                result.Story__c = this.storyId;
            return result;
        }
    }
}