src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Authorized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget Authorized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Minimum_Viable_Score__c</fullName>
        <label>Minimum Viable Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Possible_Score__c</fullName>
        <label>Possible Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Commitment__c</fullName>
        <description>% of utilization required/expected (e.g. 25%)</description>
        <inlineHelpText>% of utilization required/expected (e.g. 25%)</inlineHelpText>
        <label>Resource Commitment</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Awards__c</fullName>
        <label>Total Awards</label>
        <summarizedField>Award__c.Payment__c</summarizedField>
        <summaryForeignKey>Award__c.Activity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivitySkills__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skills__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Activity Skill</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Activity Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Skills__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Duration__c</fullName>
        <label>Project Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remaining_Budget__c</fullName>
        <label>Remaining Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Offering__c</fullName>
        <label>Service Offering</label>
        <picklist>
            <picklistValues>
                <fullName>Analytics and Data Management Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Process Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Center, Workload and Cloud Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Security Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobility and Workplace Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StoryService.cls
public with sharing class StoryService implements IStoryService {

	@TestVisible private static final Integer DEFAULT_RECENT_STORIES_COUNT = 10;

	////////////////////////////////////////// Story manipulation \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	/**
	 * creates stories
	 * @param  stories List of stories to insert
	 * @return         List<Story__c>
	 */
	public List<Story__c> createStories(List<Story__c> stories) {
		insert stories;
		return stories;
	}
	/**
	 * updates stories
	 * @param  stories List of stories to update
	 * @return         List<Story__c>
	 */
	public List<Story__c> updateStories(List<Story__c> stories) {
		update stories;
		return stories;
	}
	////////////////////////////////////////// END Story manipulation \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	/**
	 * returns a list of 10 most recently created stories
	 * @return List<Story__c>
	 */
	public List<Story__c> getMostRecentlyCreatedStories() {
		return getMostRecentlyCreatedStories(DEFAULT_RECENT_STORIES_COUNT);
	}
	/**
	 *  returns a list of the most recently created stories
	 * @param  count Stories count to return
	 * @return       List<Story__c>
	 */
	public List<Story__c> getMostRecentlyCreatedStories(Integer count) {
		return [SELECT  Id,
						Name,
						Budget__c,
						Description__c,
						Service_Offering__c,
						Project_Duration__c,
						Project_Start_Date__c,
						Publisher__c,
						Remaining_Budget__c,
						Status__c  
				FROM Story__c 
				ORDER BY CreatedDate DESC 
				LIMIT :count];
	}
	/**
	 * returns a list of activities for a particular story
	 * @param  story Story object for which activities will be returned
	 * @return       List<Activity__c>
	 */
	public List<Activity__c> getActivities(Story__c story) {
		String storyId = story.Id;
		return [SELECT  Id,
						Name,
						Challenge_Type__c,
						Budget_Authorized__c,
						Cost__c,
						Description__c,
						Minimum_Viable_Score__c,
						Possible_Score__c,
						Publisher__c,
						Resource_Commitment__c,
						Status__c,
						Total_Awards__c,
						Story__c,
						hasAwards__c
				FROM Activity__c WHERE Story__c = :storyId];
	}
	/**
	 * returns a list of stories based on the skills of the associated activities
	 * @param  skills List of skills for which stories will be searched
	 * @return        List<Story__c>
	 */
	public List<Story__c> search(List<Skills__c> skills) {
		Set<Id> skillsIds = new Map<Id, Skills__c>(skills).keySet();

		List<Activity__c> activities = [SELECT Story__c FROM Activity__c WHERE Id IN (SELECT Activity__c FROM ActivitySkills__c WHERE Skill__c IN :skillsIds)];
		Set<Id> storiesIds = new Set<Id>();
		for(Activity__c activity : activities)
			storiesIds.add(activity.Story__c);
		return [SELECT  Id,
						Name,
						Budget__c,
						Description__c,
						Service_Offering__c,
						Project_Duration__c,
						Project_Start_Date__c,
						Publisher__c,
						Remaining_Budget__c,
						Status__c  
				FROM Story__c WHERE Id IN :storiesIds];
	}
	/**
	 * returns list of stories associated with a particular user (member or publisher)
	 * @param  user User record for who stories will be returned
	 * @return      List<Story__c>
	 */
	public List<Story__c> getStoriesForUser(User user){
		// //Updated against TC30050600 
		//Collect Stories' IDs for member. NOTE: we can skip submissions, because if User has Submission for an activity he definetly has MemberActivityMilestone
		List<Activity__c> activities = [SELECT Story__c FROM Activity__c WHERE Assigned_Member__c = :user.Id OR Publisher__c = :user.Id];
		Set<Id> storiesIds = new Set<Id>();
		for(Activity__c activity : activities)
			storiesIds.add(activity.Story__c);
		return [SELECT  Id,
						Name,
						Budget__c,
						Description__c,
						Service_Offering__c,
						Project_Duration__c,
						Project_Start_Date__c,
						Publisher__c,
						Remaining_Budget__c,
						Status__c  
				FROM Story__c 
				WHERE Publisher__c = :user.Id OR Id IN :storiesIds];//Filtering stories where User is a publisher or a member
	}
}