src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Member__c</fullName>
        <label>Assigned Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities_User_Assigned_To</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registrants__c</fullName>
        <label>Registrants</label>
        <summaryForeignKey>CE_Registration__c.CE_Activity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_Story__c</fullName>
        <label>Story</label>
        <referenceTo>CE_Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Submissions__c</fullName>
        <label>Submissions</label>
        <summaryForeignKey>CE_Submission__c.CE_Activity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Story__c.object
<CustomObject>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CE_Summary_Data__c.object
<CustomObject>
    <fields>
        <fullName>Active_Activities__c</fullName>
        <label>Active Activities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active_Stories__c</fullName>
        <label>Active Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completed_Activities__c</fullName>
        <label>Completed Activities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completed_Stories__c</fullName>
        <label>Completed Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Members__c</fullName>
        <label>Number of Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Publishers__c</fullName>
        <label>Number of Publishers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <label>Timestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Activities__c</fullName>
        <label>Total Activities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Registrations__c</fullName>
        <label>Total Registrations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Reviews__c</fullName>
        <label>Total Reviews</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Stories__c</fullName>
        <label>Total Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Submissions__c</fullName>
        <label>Total Submissions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Users__c</fullName>
        <label>Total Users</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Summary Data</label>
    <nameField>
        <label>Dashboard Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Summary Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Crowd_Exchange_User_Type__c</fullName>
        <label>Crowd_Exchange_User_Type</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publisher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/CE_PublisherDashboardController.cls
/*
Class       : CE_PublisherDashboardController
Description : This class is controller for Publisher Dashboard Page
*/

public class CE_PublisherDashboardController {
    
    //Current logged-in Publisher
    public User currentUser  {get;set;}
    
    // Summary Data records populated using batch
    public CE_Summary_Data__c summaryData {get;set;}
    public Boolean isSummaryDataPresent {get;set;}
    
    // Members Skill Snapshot records populated using batch
    public List<CE_Member_Skill_Snapshot__c> listMemberSkillSnapshot {get;set;}
    public Boolean isMemberSkillSnapshotPresent {get;set;}

    // List of Story Wrapper holds active stories
    public List<StoryWrapper> listActiveStoryWrapper {get;set;}
    public Boolean isActiveStoryWrapperPresent {get;set;}
    
    // List of Completed Wrapper holds active stories
    public List<StoryWrapper> listCompletedStoryWrapper {get;set;}
    public Boolean isCompletedStoryWrapperPresent {get;set;}
    
    // List of developers
    public List<User> listDeveloper {get;set;}
    public Boolean isDeveloperPresent {get;set;}
    
    //total member count
    public Integer totalMembers {get;set;}
    
    public CE_PublisherDashboardController(){
        
        //Initialization of Variables and List.
        isSummaryDataPresent = false;
        isMemberSkillSnapshotPresent = false;
        listMemberSkillSnapshot = new List<CE_Member_Skill_Snapshot__c>();
        currentuser = new User();
        
        listActiveStoryWrapper = new List<StoryWrapper>(); 
        isActiveStoryWrapperPresent = false;
        
        listCompletedStoryWrapper = new List<StoryWrapper>(); 
        isCompletedStoryWrapperPresent = false;
        
        isDeveloperPresent = false;
        totalMembers = 0;
        
        try{
            
            // Fetch current user information
            currentuser = [Select Id,Name,Crowd_Exchange_User_Type__c,Email from User where Id=:userinfo.getuserId()]; 
            
            
            // Fetch Summary Data records populated using batch
            list<CE_Summary_Data__c> listSummaryData = [SELECT Active_Stories__c,Completed_Activities__c,Completed_Stories__c,Total_Users__c,
                                                     Id,Name,Number_of_Members__c,Number_of_Publishers__c,Timestamp__c,Total_Activities__c,
                                                     Total_Registrations__c,Total_Reviews__c,Total_Stories__c,Total_Submissions__c,Active_Activities__c 
                                                     FROM CE_Summary_Data__c where CreatedDate = TODAY limit:Limits.getLimitQueryRows()- Limits.getQueryRows() ];
            List<User> listMembers = [Select Id,Name,Crowd_Exchange_User_Type__c,Email from User where Crowd_Exchange_User_Type__c = :CE_Constants.MEMBER limit:Limits.getLimitQueryRows()- Limits.getQueryRows() ];  
            if(listMembers!=null && listMembers.size()>0){
                totalMembers = listMembers.size();
            }
            if(listSummaryData!=null && listSummaryData.size()>0){
                summaryData = listSummaryData[0];
                isSummaryDataPresent = true;
            }
            
            // Fetch Members Skill Snapshot records populated using batch
            listMemberSkillSnapshot = [Select Id,Member_Count__c,Skill_Name__c
                                       from CE_Member_Skill_Snapshot__c where Skill_Name__c!='' and Skill_Name__c!=null and CreatedDate = TODAY limit:Limits.getLimitQueryRows()- Limits.getQueryRows() ];
            if(listMemberSkillSnapshot!=null && listMemberSkillSnapshot.size()>0){
                isMemberSkillSnapshotPresent = true;
            }
            
            //Fetch Active Stories to show on page  
            Set<Id> setDeveloperId = new Set<Id>();
            List<CE_Story__c> listActiveStory = filterActiveStories();
            if(listActiveStory!=null && listActiveStory.size()>0){
                for(CE_Story__c story: listActiveStory){
                    
                    // Adding Story and its related Activities to Wrapper
                    StoryWrapper storyWrap = new StoryWrapper();
                    if(story.Activities__r!=null && story.Activities__r.size()>0){
                        List<CE_Activity__c> listActivity = new List<CE_Activity__c>();
                        for(CE_Activity__c activity: story.Activities__r){
                            if(activity.Publisher__c!=null && activity.Publisher__c == userinfo.getuserId()){
                                listActivity.add(activity);
                            }
                            if(activity.Assigned_Member__c!=null){
                                setDeveloperId.add(activity.Assigned_Member__c);
                            }
                        }
                        if(listActivity.size()>0){
                            storyWrap.listActivity = listActivity;
                            storyWrap.isActivityPresent = true;
                        }
                    }
                    storyWrap.story = story;
                    listActiveStoryWrapper.add(storyWrap);
                }
            }
            if(listActiveStoryWrapper!=null && listActiveStoryWrapper.size()>0){
                isActiveStoryWrapperPresent = true;
            }
            
            //Fetch Completed Stories to show on page  
            List<CE_Story__c> listCompletedStory = filterCompletedStories();
            if(listCompletedStory!=null && listCompletedStory.size()>0){
                for(CE_Story__c story: listCompletedStory){
                    // Adding Story and its related Activities to Wrapper
                    StoryWrapper storyWrap = new StoryWrapper();
                    if(story.Activities__r!=null && story.Activities__r.size()>0){
                        List<CE_Activity__c> listActivity = new List<CE_Activity__c>();
                        for(CE_Activity__c activity: story.Activities__r){
                            if(activity.Publisher__c!=null && activity.Publisher__c == userinfo.getuserId()){
                                listActivity.add(activity);   
                            }
                            if(activity.Assigned_Member__c!=null){
                                setDeveloperId.add(activity.Assigned_Member__c);
                            }
                        }
                        if(listActivity.size()>0){
                            storyWrap.listActivity = listActivity;
                            storyWrap.isActivityPresent = true;
                        }  
                    }
                    storyWrap.story = story;
                    listCompletedStoryWrapper.add(storyWrap);
                }  
            }
            if(listCompletedStoryWrapper!=null && listCompletedStoryWrapper.size()>0){
                isCompletedStoryWrapperPresent = true;
            } 
            
            //Fetch list of developers
            listDeveloper = fetchDevelopers(setDeveloperId);
            if(listDeveloper!=null && listDeveloper.size()>0){
                isDeveloperPresent = true;           
            }
            
        // Catch if exception caused	
		}catch(Exception ex){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,ex.getMessage()));
		} 
    }
    
     /*
        Method to fetch Stories related to publisher which are active
    */
    public List<CE_Story__c> filterActiveStories(){
        List<CE_Story__c> listStory = [Select Id,Name,(Select Id,CE_Story__r.Name,Status__c,Registrants__c,Submissions__c,CE_Story__c,
                            Name,Assigned_Member__c,Publisher__c from Activities__r)
                            from CE_Story__c where Publisher__c = :userinfo.getuserId() and Status__c!= :CE_Constants.STATUS_CANCELED  and Status__c!= :CE_Constants.STATUS_COMPLETED 
                            limit:Limits.getLimitQueryRows()- Limits.getQueryRows() ];
        return listStory;
    }

    /*
        Method to fetch Stories related to publisher which are Completed
    */
    public List<CE_Story__c> filterCompletedStories(){
        List<CE_Story__c> listStory = [Select Id,Name,(Select Id,CE_Story__r.Name,Status__c,Registrants__c,Submissions__c,CE_Story__c,
                            Name,Assigned_Member__c,Publisher__c from Activities__r)
                            from CE_Story__c where Publisher__c = :userinfo.getuserId() and Status__c= :CE_Constants.STATUS_COMPLETED 
                            limit:Limits.getLimitQueryRows()- Limits.getQueryRows() ];
        return listStory;
    }
    
    /*
        Method to fetch Developers who have worked with publisher
    */
    public List<User> fetchDevelopers(Set<Id> setUserId){
        if(setUserId!=null && setUserId.size()>0){
            List<User> listUsers = [Select Id,Name,Crowd_Exchange_User_Type__c,SmallPhotoUrl  
                                       from User where Crowd_Exchange_User_Type__c = :CE_Constants.MEMBER and Id IN :setUserId 
                                       limit:Limits.getLimitQueryRows()- Limits.getQueryRows() ];
                                      
            return listUsers;
        }
        return null;
    }
    
    /*
        Wrapper class to hold Story and its related Activities information
    */
    public class StoryWrapper{
        
        public CE_Story__c story {get;set;}
        public List<CE_Activity__c> listActivity {get;set;}
        public Boolean isActivityPresent {get;set;}
        
        public StoryWrapper(){
            listActivity = new List<CE_Activity__c>();
            isActivityPresent = false;
        }
    }

}