src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Possible_Score__c</fullName>
        <label>Possible Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityMilestones__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity Milestone</label>
    <nameField>
        <displayFormat>AM-{000000000}</displayFormat>
        <label>ActivityMilestones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivitySkills__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skills__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Activity Skill</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Activity Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Submission__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation_Percentage__c</fullName>
        <label>Evaluation Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <label>Placement</label>
        <picklist>
            <picklistValues>
                <fullName>1st</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Score__c</fullName>
        <label>Submission Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submitting_Member__c</fullName>
        <label>Submitting Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/InternalProjectSkill__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Project__c</fullName>
        <label>Internal Project</label>
        <referenceTo>Internal_Project__c</referenceTo>
        <relationshipLabel>Internal Project Skills</relationshipLabel>
        <relationshipName>Internal_Project_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skills__c</referenceTo>
        <relationshipLabel>Internal Project Skills</relationshipLabel>
        <relationshipName>Internal_Project_Skills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Internal Project Skill</label>
    <nameField>
        <displayFormat>IPS-{000000000}</displayFormat>
        <label>InternalProjectSkill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Project Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skills__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Project__c</fullName>
        <label>Internal Project</label>
        <referenceTo>Internal_Project__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Evaluation_Percentage__c</fullName>
        <label>Evaluation Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Score__c</fullName>
        <label>Submission Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submitting_Member__c</fullName>
        <label>Submitting Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Crowd_Exchange_About_Me__c</fullName>
        <label>Crowd Exchange About Me</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Crowd_Exchange_Organization__c</fullName>
        <label>Crowd Exchange Organization</label>
        <length>120</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/UserSkill__c.object
<CustomObject>
    <fields>
        <fullName>Experience_Level__c</fullName>
        <label>Experience Level</label>
        <picklist>
            <picklistValues>
                <fullName>Entry Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skills__c</referenceTo>
        <relationshipLabel>User Skills</relationshipLabel>
        <relationshipName>User_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Skill</label>
    <nameField>
        <displayFormat>US-{000000000}</displayFormat>
        <label>UserSkill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CrowdExchange_MemberMemberProfile.cls
/*
Class       : CrowdExchange_MemberMemberProfile
Description : This class is controller for Member-Member profile page
*/

public class CrowdExchange_MemberMemberProfile {
    
    //Current logged-in member
    public User currentMember {get;set;}
    
    //User SKills related to member
    public List<UserSkill__c> listMemberSkills {get;set;}
    public Boolean isMemberSkillPresent {get;set;}

    //Internal Project related to member
    public List<Internal_Project__c> listInternalProjects {get;set;}
    public Boolean isInternalProjectsPresent {get;set;}
    
    //Current Activity related to member
    public List<Activity__c> listCurrentActivity {get;set;}
    public List<ActiveActivityWrapper> listCurrentActivityWrapper {get;set;}
    public Boolean isCurrentActivityPresent {get;set;}
    
    //Completed Activity related to member
    public List<CompletedActivityWrapper> listCompletedActivityWrapper {get;set;}
    public List<Activity__c> listCompletedActivity {get;set;}
    public Boolean isCompletedActivityPresent {get;set;}    
    
    //Boolean variables to check if records are present or not
    public Integer currentActivity {get;set;}
    public Integer completedActivityCount {get;set;}
    public Integer totalActivity {get;set;}
    public Integer totalMemberSkill {get;set;}
    public String userId {get;set;}
    
    //email template record amd email related information
    public EmailTemplate emailTemplate {get;set;}
    public List<ActivityWrapper> listActivityWrapper{get;set;}
    public String subject {get;set;}
    public String body {get;set;}
    public String bodyAll {get;set;}
    public String email {get;set;}
    public String selectedUser {get;set;}
    public Boolean isPublisherActivityPresent {get;set;}
    
    //Holds Banner image of user
    public Attachment headerImageAttachment {get;set;}
    
    public CrowdExchange_MemberMemberProfile(){
        
        //Initialization of Variables and List.
        currentMember = new User();
        userId = '';
        currentActivity = 0;    
        totalActivity = 0; 
        totalMemberSkill = 0; 
        completedActivityCount = 0;
        
        //Get User if from page parameter and fetching user fields, 
       //If parameter is not present fetch information of current user
        userId = ApexPages.currentPage().getParameters().get(Constants.ID);
        if(userId!=null && userId!=''){
            currentMember = [Select Id,Title,Name,Email,Crowd_Exchange_Organization__c,AboutMe,Phone,SmallPhotoUrl,FullPhotoUrl,Crowd_Exchange_About_Me__c 
                             from User where Id =: userId limit 1];
        }else{
            currentMember = [Select Id,Title,Name,Email,Crowd_Exchange_Organization__c,AboutMe,Phone,SmallPhotoUrl,FullPhotoUrl,Crowd_Exchange_About_Me__c 
                             from User where Id =: userinfo.getuserId() limit 1];
        }  
        userId = currentMember.Id;
        
        //Fetch Member skills to show on page
        isMemberSkillPresent = false;                 
        listMemberSkills = new List<UserSkill__c>();
        listMemberSkills = filterMemberSkills();
        if(listMemberSkills!=null && listMemberSkills.size()>0){
            isMemberSkillPresent = true;
            totalMemberSkill = listMemberSkills.size();
        }
        
        //Fetch Internal Projects to show on page    
        listInternalProjects = new List<Internal_Project__c>();
        listInternalProjects = filterInternalProjects();
        if(listInternalProjects!=null && listInternalProjects.size()>0){
            isInternalProjectsPresent = true;
        }
        
         //Fetch Current Activities to show on page
        isCurrentActivityPresent = false;                 
        listCurrentActivity = new List<Activity__c>();
        listCurrentActivity = filterCurrentActivity();
        listCurrentActivityWrapper = new List<ActiveActivityWrapper>();
        listCurrentActivityWrapper = populateActivityWrapperList(listCurrentActivity);
        if(listCurrentActivity!=null && listCurrentActivity.size()>0){  
            isCurrentActivityPresent = true;
            currentActivity = listCurrentActivity.size();
            totalActivity += currentActivity;
        }
        
        //Fetch Completed Activities to show on page
        isCompletedActivityPresent = false;      
        listCompletedActivityWrapper = new List<CompletedActivityWrapper>();
        List<Activity__c> listCompletedActivity = new List<Activity__c>();
        listCompletedActivity = filterCompletedActivity();
        if(listCompletedActivity!=null && listCompletedActivity.size()>0){
            for(Activity__c activity : listCompletedActivity){
                CompletedActivityWrapper cActivityWrapper = new CompletedActivityWrapper(activity);
                for(Submission__c submission: activity.Submissions__r){
                    if(submission.Submitting_Member__c == currentMember.Id){
                        cActivityWrapper.submission = submission;
                    }
                }
                if(activity.ActivityMilestones__r != null && activity.ActivityMilestones__r.size() == Constants.NUMBER_OF_MILESTONES){
	    		    	cActivityWrapper.startDate = activity.ActivityMilestones__r[1].Completed_Date__c;
		    		    cActivityWrapper.endDate = activity.ActivityMilestones__r[7].Completed_Date__c;
	    		}
	    		
	    		listCompletedActivityWrapper.add(cActivityWrapper);
	    		
	         }
             isCompletedActivityPresent = true;
             completedActivityCount = listCompletedActivity.size();  
             totalActivity += listCompletedActivity.size();    
                
        }
            
        
        //Fetch USer banner image from custom object
        List<User_Header_Picture__c> listUserHeaderPicture = [Select Id,(Select Id, ParentId From Attachments) from User_Header_Picture__c 
                                                              where User__c =: currentMember.Id limit:Limits.getLimitQueryRows()- Limits.getQueryRows()];
        if(listUserHeaderPicture!=null && listUserHeaderPicture.size()>0){
            User_Header_Picture__c userHeaderPicture = listUserHeaderPicture[0];
            if(userHeaderPicture.Attachments!=null && userHeaderPicture.Attachments.size()>0){
                headerImageAttachment = userHeaderPicture.Attachments[0];
            }
        }
        
        //Fetch Activit list
        fetchActivityList();
                         
    }
    
    /*
        Method to fetch User skills related to current user
    */
    public List<UserSkill__c> filterMemberSkills(){  
        List<UserSkill__c> listUserSkills = [Select Id,Experience_Level__c,Member__c,Skill__r.Name
                                             from UserSkill__c where Member__c =: userId and Skill__c!=null 
                                             limit:Limits.getLimitQueryRows()- Limits.getQueryRows()];
        return listUserSkills;
    }

    /*
        Method to fetch Internal Projects to current user
    */
    public List<Internal_Project__c> filterInternalProjects(){
        List<Internal_Project__c> listInternalProject = [Select Id,Description__c,Name,(Select Id,Skill__r.Name from Internal_Project_Skills__r)
                                                         from Internal_Project__c where Member__c =: userId 
                                                         limit:Limits.getLimitQueryRows()- Limits.getQueryRows()];
        return listInternalProject;
    }
    
    /*
        Method to fetch Active Activities related to current user
    */
    public List<Activity__c> filterCurrentActivity(){  
        List<Activity__c> listActivity = [Select Id,Name,Possible_Score__c,Cost__c,
                                          (Select Id,Skill__r.Name from Activity_Skills__r),
                                          (Select Id, Name, Activity__c, Milestone__c, Completed_Date__c, Scheduled_Date__c From ActivityMilestones__r) 
                                          from Activity__c where Status__c != :Constants.STATUS_DRAFT and Status__c != :Constants.STATUS_COMPLETED  and Status__c != :Constants.STATUS_CANCELED 
                                          and Assigned_Member__c =: userId limit:Limits.getLimitQueryRows()- Limits.getQueryRows()];
        return listActivity;
    }
    
    /*
        Method to fetch Completed Activities related to current user
    */ 
    public List<Activity__c> filterCompletedActivity(){
        List<Activity__c> listActivity = [Select Id,Name,Possible_Score__c,Cost__c,
                                          (Select Id,Skill__r.Name from Activity_Skills__r),
                                          (Select Id, Name, Activity__c, Milestone__c, Completed_Date__c, Scheduled_Date__c From ActivityMilestones__r),
                                          (Select id,Evaluation_Percentage__c,Placement__c,Submission_Score__c,Submitting_Member__c from Submissions__r)
                                          from Activity__c where Status__c =  :Constants.STATUS_COMPLETED and Assigned_Member__c =: userId 
                                          limit:Limits.getLimitQueryRows()- Limits.getQueryRows()];  
        return listActivity;
    }
    
        
    /*
        Method to fetch Activity List to show when publisher clicks email button on member tabs 
    */    
    public void fetchActivityList(){

            try{
                User user = [Select Id,Name,Email from User where Id =:currentMember.Id];
                email = user.email;  
                
                // Fetch email template
                List<EmailTemplate> listEmailTemplate = [Select Id,Body,Subject from EmailTemplate where Name = :Constants.MEMBER_SEARCH];
                if(listEmailTemplate!=null &&listEmailTemplate.size()>0){
                    emailTemplate = listEmailTemplate[0];
                    subject = emailTemplate.Subject;
                    body = emailTemplate.Body;
                }
                
                // Website url from custom setting
                CrowdExchangeSettings__c ceWebsite = CrowdExchangeSettings__c.getOrgDefaults();  
                String urlWebsite = ceWebsite.Site_Url__c;
                listActivityWrapper = new List<ActivityWrapper>();
                
                //List of all activities for a user
                List<Activity__c> listActivities = [Select Id,Name from Activity__c where Publisher__c = :userinfo.getuserId() and ( Status__c = :Constants.STATUS_IN_REGISTRATION or Status__c = :Constants.STATUS_PUBLIC )
                                                    limit:Limits.getLimitQueryRows()- Limits.getQueryRows() ];
                if(listActivities!=null && listActivities.size()>0){
                    for(Activity__c activity : listActivities){
                
                        String mergedBody = body.replace('{{userFirstName}}:', '{!User.Name}:%0A');
                        mergedBody = mergedBody.replace('{!User.Name}', user.Name);
                        if(urlWebsite!=null){
                            mergedBody = mergedBody.replace('{!$Setup.CrowdExchangeSettings__c.Site_Url__c}', urlWebsite);
                        }
                        mergedBody = mergedBody.replace('{{activityName}}', activity.Name); 
                         
                        ActivityWrapper activityWrap = new ActivityWrapper(activity.Id, activity.Name,mergedBody,user.Email);
                        
                        listActivityWrapper.add(activityWrap);  
                    }
                }
                
                //form email body with activity name mentioned in body
                bodyAll = body.replace('{{userFirstName}}:', '{!User.Name}:%0A');
                bodyAll = bodyAll.replace('{!User.Name}', user.Name); 
                if(urlWebsite!=null){  
                    bodyAll = bodyAll.replace('{!$Setup.CrowdExchangeSettings__c.Site_Url__c}', urlWebsite);
                }
                bodyAll = bodyAll.replace('{{activityName}}', '<enter activity name>');
                        
                if(listActivityWrapper!=null && listActivityWrapper.size()>0){
                    isPublisherActivityPresent = true;  
                }
                
            // Catch if exception caused  	
    		}catch(Exception ex){
    			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,ex.getMessage()));
    		} 
    }
    
    /*
        Activity Wrapper holds activity information   
    */
    public class ActivityWrapper{
    	public String activityId {get;set;}
        public String activityName {get;set;}
        public String activityBody {get;set;}
        public String email {get;set;}
        public Date startDate {get;set;}
        public Date endDate {get;set;}
        public ActivityWrapper(String aId, String aName,String aBody,String userEmail){
            activityId = aId;
            activityName = aName;
            activityBody = aBody;
            email = userEmail;
        }
    }
    
    /*
        Completed Activity Wrapper holds completed activity information   
    */
    public class ActiveActivityWrapper{  
        
        public Activity__c activity {get;set;}
        public Date startDate {get;set;}
        public Date endDate {get;set;}
       
    }
        
    public List<ActiveActivityWrapper> populateActivityWrapperList(List<Activity__c> activityList){
    	
    	List<ActiveActivityWrapper> awl = new List<ActiveActivityWrapper>();
    	for(Activity__c a: activityList){
    		ActiveActivityWrapper wrapper = new ActiveActivityWrapper();
    		wrapper.activity = a;
    		if(a.ActivityMilestones__r != null && a.ActivityMilestones__r.size() == Constants.NUMBER_OF_MILESTONES){
	    		    wrapper.startDate = a.ActivityMilestones__r[1].Scheduled_Date__c;
	    		    wrapper.endDate = a.ActivityMilestones__r[7].Scheduled_Date__c;
    		}
    		awl.add(wrapper);
    		
    	}
    	return awl;
    	
    }
    
    
    
    
    /*
        Completed Activity Wrapper holds completed activity information   
    */
    public class CompletedActivityWrapper{  
        
        public Activity__c completedActivity {get;set;}
        public Submission__c submission {get;set;}
        public Date startDate {get;set;}
        public Date endDate {get;set;}
        public CompletedActivityWrapper(Activity__c cActivity){
            completedActivity = cActivity;
        }
        
    }
    
}