src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Member_Skill_Snapshot__c.object
<CustomObject>
    <label>Member Skill Snapshot</label>
    <nameField>
        <label>Skill Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Skill Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Skills__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UserSkill__c.object
<CustomObject>
    <label>User Skill</label>
    <nameField>
        <displayFormat>US-{000000000}</displayFormat>
        <label>UserSkill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DashboardUpdaterTest.cls
/**************************************************
* Dashboard Updater Test
* -------------------------------------------------
* Created By: Daniel Eagle (daniel.eagle@hp.com)
* Last Modified: 7/16/2015
* -------------------------------------------------
* Test methods for the Dashboard Updater.
**************************************************/ 

@isTest(SeeAllData=false)
private class DashboardUpdaterTest {
    static testMethod void updateDashboardTest() {
        // create test user object
        User userToCreate = TestDataFactory.createNewUsers(1)[0];
                                    
        // invoke User Service
        UserService userService = new UserService();
        
        // create users
        Id userId = userService.createUser(userToCreate); 
        
        // invoke Activity Service
        ActivityService activityService = new ActivityService();
        
        // create stories and activities
        Story__c story1 = TestFactory.createStory();
        Story__c story2 = TestFactory.createStory();
        story2.Status__c = 'Completed';
        Story__c story3 = TestFactory.createStory();
        insert story1;
        insert story2;
        insert story3;
        
        Activity__c activity1 = TestFactory.createActivity(story1);
        activity1.Assigned_Member__c = userId;
        Activity__c activity2 = TestFactory.createActivity(story2);
        activity2.Assigned_Member__c = userId;
        activity2.Status__c = 'Completed';
        Activity__c activity3 = TestFactory.createActivity(story3);
        activity3.Assigned_Member__c = userId;
        activity3.Status__c = 'Public';
        insert activity1;
        insert activity2;
        insert activity3;
        
        // create registration
        Registration__c registration = TestFactory.createRegisterMember(userId, activity1);
        insert registration;
        
        // create submissions
        Submission__c submission1 = TestFactory.createSubmission(activity1);
        Submission__c submission2 = TestFactory.createSubmission(activity1);
        submission2.Status__c = 'Review Complete';
        insert submission1;
        insert submission2;
        
        // create skills
        Skills__c skill1 = TestDataFactory.createSkill('C++');
        Skills__c skill2 = TestDataFactory.createSkill('Java');
        Skills__c skill3 = TestDataFactory.createSkill('JavaScript');
        Skills__c skill4 = TestDataFactory.createSkill('Python');
        Skills__c skill5 = TestDataFactory.createSkill('Ruby');
        Skills__c skill6 = TestDataFactory.createSkill('C#');
        
        // create user skills
        UserSkill__c userSkill1 = TestDataFactory.createUserSkill(userId, skill1.Id);
        UserSkill__c userSkill2 = TestDataFactory.createUserSkill(userId, skill2.Id);
        UserSkill__c userSkill3 = TestDataFactory.createUserSkill(userId, skill3.Id);
        UserSkill__c userSkill4 = TestDataFactory.createUserSkill(userId, skill4.Id);
        UserSkill__c userSkill5 = TestDataFactory.createUserSkill(userId, skill5.Id);
        UserSkill__c userSkill6 = TestDataFactory.createUserSkill(userId, skill6.Id);
        
        // add user skills to list
        List<UserSkill__c> userSkills = new List<UserSkill__c>();
        userSkills.add(userSkill1);
        userSkills.add(userSkill2);
        userSkills.add(userSkill3);
        userSkills.add(userSkill4);
        userSkills.add(userSkill5);
        
        // begin test
        Test.startTest();
        DashboardUpdater dashboardUpdater = new DashboardUpdater();
        dashboardUpdater.execute();
        Test.stopTest();
        
        // verify results
        System.assertEquals(2, [SELECT count() FROM Story__c WHERE Status__c != 'Completed' 
        		AND Status__c != 'Canceled' AND IsDeleted = false]);
        System.assertEquals(1, [SELECT count() FROM Activity__c WHERE Status__c != 'Completed' 
        		AND Status__c != 'Draft' AND IsDeleted = false]);
        System.assertEquals(1, [SELECT count() FROM Activity__c WHERE Status__c = 'Completed' 
        		AND IsDeleted = false]);
        System.assertEquals(1, [SELECT count() FROM Story__c WHERE Status__c = 'Completed' 
        		AND IsDeleted = false]);
        System.assertEquals(3, [SELECT count() FROM Activity__c WHERE IsDeleted = false]);
        System.assertEquals(3, [SELECT count() FROM Story__c WHERE IsDeleted = false]);
        System.assertEquals(1, [SELECT count() FROM Registration__c]);
        System.assertEquals(1, [SELECT count() FROM Submission__c WHERE Status__c = 'Review Complete']);
        System.assertEquals(2, [SELECT count() FROM Submission__c]);
        System.assertEquals(6, [SELECT count() FROM Member_Skill_Snapshot__c]);
    }
}