src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityMilestones__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity Milestone</label>
    <nameField>
        <displayFormat>AM-{000000000}</displayFormat>
        <label>ActivityMilestones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Timestamp__c</fullName>
        <label>Submission Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Submitting_Member__c</fullName>
        <label>Submitting Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WorkflowManagerTest.cls
/**
 * Test Class for WorkflowManager class and ActivityMonitoringBatch
 * Added against TC30050600
 */
@isTest
private class WorkflowManagerTest {
	static Activity__c activity;
	
	// Creating test data
    static void createTestData(){

        //Creating the user for Publisher field for Activity and Story objects
        User user = TestFactory.createUser();
        insert user;
        
        Story__c story = TestFactory.createStory();
        story.Publisher__c = user.Id;
        insert story;
        
        activity = TestFactory.createActivity(story);
        activity.Publisher__c = user.Id;
        insert activity;
        
        //Creating milestones
        Milestone__c publishDateMilestone = new Milestone__c(Name = Constants.PUBLISH_DATE_MILESTONE_NAME, Display_In_Initial_Setup__c = true, Default_Time_Period__c = 1, Type__c = 'Software Development', Step_Number__c = 1);
		Milestone__c startDateMilestone = new Milestone__c(Name = Constants.START_DATE_MILESTONE_NAME, Display_In_Initial_Setup__c = true, Default_Time_Period__c = 2, Type__c = 'Software Development', Step_Number__c = 2);
		Milestone__c registrationDateMilestone = new Milestone__c(Name = Constants.REGISTRATION_DATE_MILESTONE_NAME, Display_In_Initial_Setup__c = true, Default_Time_Period__c = 2, Type__c = 'Software Development', Step_Number__c = 3);
		Milestone__c assignmentDateMilestone = new Milestone__c(Name = Constants.ASSIGNMENT_DATE_MILESTONE_NAME, Display_In_Initial_Setup__c = true, Default_Time_Period__c = 1, Type__c = 'Software Development', Step_Number__c = 4);
		Milestone__c submissionDateMilestone = new Milestone__c(Name = Constants.SUBMISSION_DATE_MILESTONE_NAME, Display_In_Initial_Setup__c = true, Default_Time_Period__c = 7, Type__c = 'Software Development', Step_Number__c = 5);
		Milestone__c reviewDateMilestone = new Milestone__c(Name = Constants.REVIEW_DATE_MILESTONE_NAME, Display_In_Initial_Setup__c = true, Default_Time_Period__c = 2, Type__c = 'Software Development', Step_Number__c = 6);
		Milestone__c acceptanceDateMilestone = new Milestone__c(Name = Constants.ACCEPTANCE_DATE_MILESTONE_NAME, Display_In_Initial_Setup__c = false, Type__c = 'Software Development', Step_Number__c = 7);
		Milestone__c endDateMilestone = new Milestone__c(Name = Constants.END_DATE_MILESTONE_NAME, Display_In_Initial_Setup__c = false, Type__c = 'Software Development', Step_Number__c = 8);

		insert new List<Milestone__c> { 
					publishDateMilestone,
				    startDateMilestone,
				    registrationDateMilestone,
				    assignmentDateMilestone,
				    submissionDateMilestone,
				    reviewDateMilestone,
				    acceptanceDateMilestone,
				    endDateMilestone
				};
        
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        activityMilestones.add(TestFactory.createActivityMilestone(activity, startDateMilestone, Date.today().addDays(-1)));
        activityMilestones.add(TestFactory.createActivityMilestone(activity, publishDateMilestone, Date.today().addDays(-1)));
        activityMilestones.add(TestFactory.createActivityMilestone(activity, registrationDateMilestone, Date.today().addDays(-1)));
        activityMilestones.add(TestFactory.createActivityMilestone(activity, assignmentDateMilestone, Date.today().addDays(-1)));
        activityMilestones.add(TestFactory.createActivityMilestone(activity, submissionDateMilestone, Date.today().addDays(-1)));
        activityMilestones.add(TestFactory.createActivityMilestone(activity, reviewDateMilestone, Date.today().addDays(-1)));
        activityMilestones.add(TestFactory.createActivityMilestone(activity, acceptanceDateMilestone, Date.today().addDays(-1)));
        activityMilestones.add(TestFactory.createActivityMilestone(activity, endDateMilestone, Date.today().addDays(-1)));
        
        insert activityMilestones;
    }

	/*
		test processActivities method called from ActivityMonitoringBatch
	*/
    static testMethod void processActivities_BatchCall_Test() {
        createTestData();
        
        Test.startTest();
        
        System.assertEquals(Constants.STATUS_DRAFT, activity.Status__c, 'Initail status as Draft');
        
        ActivityMonitoringBatch amb = new ActivityMonitoringBatch();
		database.executeBatch(amb);
        Test.stopTest();
        
        Activity__c updatedActivity = [Select Status__c from Activity__c where id =: activity.Id];
        System.assert(updatedActivity != null);
        System.assertEquals(Constants.STATUS_IN_REGISTRATION, updatedActivity.Status__c, 'Updated status as In Registration');
    }
	
	/*
		test processActivities method setting activity status as In Registration
	*/
    static testMethod void processActivities_Status_In_Registration_Test() {
        createTestData();
        
        Test.startTest();
        
        System.assertEquals(Constants.STATUS_DRAFT, activity.Status__c, 'Initail status as Draft');
        
        WorkflowManager.processActivities(new List<Activity__c> {activity} );
        
        Activity__c updatedActivity = [Select Status__c from Activity__c where id =: activity.Id];
        
        System.assertEquals(Constants.STATUS_IN_REGISTRATION, updatedActivity.Status__c, 'Updated status as In Registration');
        
        Test.stopTest();
    }
    
    /*
		test processActivities method setting activity status as In Assignment
	*/
    static testMethod void processActivities_Status_In_Assignment_Test() {
        createTestData();
        User user = TestFactory.createUser();
        insert user;
        
        // adding a registration record.
        Registration__c registration = TestFactory.createRegisterMember(user.Id, activity);
        insert registration;
        
        Test.startTest();
        
        System.assertEquals(Constants.STATUS_DRAFT, activity.Status__c, 'Initail status as Draft');
        
        WorkflowManager.processActivities(new List<Activity__c> {activity} );
        
        Activity__c updatedActivity = [Select Status__c from Activity__c where id =: activity.Id];
        
        System.assertEquals(Constants.STATUS_IN_ASSIGNMENT, updatedActivity.Status__c, 'Updated status as In Assignment');
        
        Test.stopTest();
    }
    
    /*
		test processActivities method setting activity status as In Review
	*/
    static testMethod void processActivities_Status_In_Review_Test() {
        createTestData();
        User user = TestFactory.createUser();
        insert user;
        
        // adding a registration record.
        Registration__c registration = TestFactory.createRegisterMember(user.Id, activity);
        insert registration;
        
        activity.Assigned_Member__c = user.Id;
        update activity;
        
        Submission__c submission = TestFactory.createSubmission(activity);
        submission.Submitting_Member__c = user.Id;
        submission.Submission_Timestamp__c = DateTime.now().addHours(-48);
        insert submission;
        
        Test.startTest();
        
        System.assertEquals(Constants.STATUS_DRAFT, activity.Status__c, 'Initail status as Draft');
        
        WorkflowManager.processActivities(new List<Activity__c> {activity} );
        
        Activity__c updatedActivity = [Select Status__c from Activity__c where id =: activity.Id];
        
        System.assertEquals(Constants.STATUS_IN_REVIEW, updatedActivity.Status__c, 'Updated status as In Review');
        
        Test.stopTest();
    }
    
    /*
		test processSubmissionReview method will all activity Summissions marked as Review Complete
	*/
    static testMethod void processSubmissionReview_AllStatus_ReviewComplete_Test() {
        createTestData();
        User user = TestFactory.createUser();
        insert user;
        
        // adding a registration record.
        Registration__c registration = TestFactory.createRegisterMember(user.Id, activity);
        insert registration;
        
        activity.Assigned_Member__c = user.Id;
        update activity;
        
        Submission__c submission1 = TestFactory.createSubmission(activity);
        submission1.Submitting_Member__c = user.Id;
        submission1.Submission_Timestamp__c = DateTime.now().addHours(-48);
        Submission__c submission2 = TestFactory.createSubmission(activity);
        submission2.Submitting_Member__c = user.Id;
        submission2.Submission_Timestamp__c = DateTime.now().addHours(-48);
        insert new List<Submission__c>{submission1, submission2};
        
        Test.startTest();
        
        System.assertEquals(Constants.STATUS_DRAFT, activity.Status__c, 'Initail status as Draft');
        
        // Calling processActivities process initail status 
        WorkflowManager.processActivities(new List<Activity__c> {activity} );
        
        Activity__c updatedActivity = [Select Status__c from Activity__c where id =: activity.Id];
        System.assertEquals(Constants.STATUS_IN_REVIEW, updatedActivity.Status__c, 'Updated status as In Review');
        
        // Setting submission1 status as Review Complete 
        submission1.Status__c = Constants.REVIEW_COMPLETE_STATUS;
        // Setting submission2 status as Review Complete 
        submission2.Status__c = Constants.REVIEW_COMPLETE_STATUS;
        
        update new List<Submission__c>{submission1, submission2};
        
        updatedActivity = [Select Status__c from Activity__c where id =: activity.Id];
        
        // Activity will be marked as complete as all submission are review complete, which further update
        // activity status as Accept and finaly as complete. 
        System.assertEquals(Constants.STATUS_COMPLETE, updatedActivity.Status__c, 'Updated status as Complete');
        
        Test.stopTest();
    }
    
    /*
		test processSubmissionReview method will one of the activity Summissions not Review Complete
	*/
    static testMethod void processSubmissionReview_NotAllStatus_ReviewComplete_Test() {
        createTestData();
        User user = TestFactory.createUser();
        insert user;
        
        // adding a registration record.
        Registration__c registration = TestFactory.createRegisterMember(user.Id, activity);
        insert registration;
        
        activity.Assigned_Member__c = user.Id;
        update activity;
        
        Submission__c submission1 = TestFactory.createSubmission(activity);
        submission1.Submitting_Member__c = user.Id;
        submission1.Submission_Timestamp__c = DateTime.now().addHours(-48);
        
        Submission__c submission2 = TestFactory.createSubmission(activity);
        submission2.Submitting_Member__c = user.Id;
        submission2.Submission_Timestamp__c = DateTime.now().addHours(-48);
        insert new List<Submission__c>{submission1, submission2};
        
        Test.startTest();
        
        System.assertEquals(Constants.STATUS_DRAFT, activity.Status__c, 'Initail status as Draft');
        
        // Calling processActivities process initail status 
        WorkflowManager.processActivities(new List<Activity__c> {activity} );
        
        Activity__c updatedActivity = [Select Status__c from Activity__c where id =: activity.Id];
        System.assertEquals(Constants.STATUS_IN_REVIEW, updatedActivity.Status__c, 'Updated status as In Review');
        
        // Setting submission1 status as Review Complete 
        submission1.Status__c = Constants.REVIEW_COMPLETE_STATUS;
        // Setting submission2 status as Ready To Review 
        submission2.Status__c = Constants.READY_TO_REVIEW_STATUS;
        
        update new List<Submission__c>{submission1, submission2};
        
        updatedActivity = [Select Status__c from Activity__c where id =: activity.Id];
        
        // There will be no update to activity status as there is on submission not review 
        System.assertEquals(Constants.STATUS_IN_REVIEW, updatedActivity.Status__c, 'Updated status as In Review');
        
        Test.stopTest();
    }
}