src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget_Authorized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget Authorized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Minimum_Viable_Score__c</fullName>
        <label>Minimum Viable Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Possible_Score__c</fullName>
        <label>Possible Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Commitment__c</fullName>
        <description>% of utilization required/expected (e.g. 25%)</description>
        <inlineHelpText>% of utilization required/expected (e.g. 25%)</inlineHelpText>
        <label>Resource Commitment</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Awards__c</fullName>
        <label>Total Awards</label>
        <summarizedField>Award__c.Payment__c</summarizedField>
        <summaryForeignKey>Award__c.Activity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityMilestones__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity Milestone</label>
    <nameField>
        <displayFormat>AM-{000000000}</displayFormat>
        <label>ActivityMilestones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivitySkills__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skills__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Activity Skill</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Activity Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Award</label>
    <nameField>
        <displayFormat>Award-{000000000}</displayFormat>
        <label>Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Default_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Requirement_Weight__c</fullName>
        <label>Requirement Weight</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Application Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Default Requirement</label>
    <nameField>
        <label>Default Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Requirement_Evaluation__c</fullName>
        <label>Requirement Evaluation</label>
        <picklist>
            <picklistValues>
                <fullName>Meets requirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Somewhat satisfies requirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does not meet requirement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requirement_Weight__c</fullName>
        <description>Importance of a particular requirement</description>
        <inlineHelpText>Importance of a particular requirement</inlineHelpText>
        <label>Requirement Weight</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Application Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Skills__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Project__c</fullName>
        <label>Internal Project</label>
        <referenceTo>Internal_Project__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserActivityMilestone__c.object
<CustomObject>
    <fields>
        <fullName>ActivityMilestones__c</fullName>
        <label>ActivityMilestone</label>
        <referenceTo>ActivityMilestones__c</referenceTo>
        <relationshipName>MemberActivityMilestones</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipName>MemberActivites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MemberActivites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Activity Milestone</label>
    <nameField>
        <displayFormat>UAM-{000000000}</displayFormat>
        <label>UserActivityMilestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Activity Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ActivityService.cls
public with sharing class ActivityService implements IActivityService {

    ////////////////////////////////////////// Activity \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    /**
     * creates activities
     * @param  activities list of activities to insert
     * @return            created list of activies with ids
     */
    public List<Activity__c> createActivities(List<Activity__c> activities) {
        insert activities;
        return activities;
    }
    /**
     * updates activities
     * @param  activities list of activities to insert
     * @return            updated list of activies
     */
    public List<Activity__c> updateActivities(List<Activity__c> activities) {
        update activities;
        return activities;
    }
    /**
     * deletes activities
     * @param activities list of activities to delete
     */
    public void deleteActivities(List<Activity__c> activities) {
        delete activities;
    }
    /**
     * searches for activities based on a list of skills
     * @param  skills list of skills for Activities' filter
     * @return        List<Activity__c> 
     */
    public List<Activity__c> search(List<Skills__c> skills) {
        Set<Id> skillsIds = new Map<Id,Skills__c>(skills).keySet();
        return [SELECT Name,
                        Activity_Type__c,
                        Budget_Authorized__c,
                        Cost__c,
                        Description__c,
                        Minimum_Viable_Score__c,
                        Possible_Score__c,
                        Publisher__c,
                        Resource_Commitment__c,
                        Status__c,
                        Total_Awards__c,
                        Story__c
                FROM Activity__c 
                WHERE Id IN (SELECT Activity__c FROM ActivitySkills__c WHERE Skill__c IN :skillsIds)];
    }
    /**
     * gets a collections of activities associated with a particular user.  The user might be a publisher or a member.
     * @param  user User record(member or publisher)
     * @return      List<Activity__c>
     */
    public List<Activity__c> getActivitiesForUser(User user) {

        Map<Id, Activity__c> activitiesMap = new Map<Id, Activity__c>();
        //Getting ACtivities where user is Member
        activitiesMap.putAll([SELECT Name,
                                    Activity_Type__c,
                                    Budget_Authorized__c,
                                    Cost__c,
                                    Description__c,
                                    Minimum_Viable_Score__c,
                                    Possible_Score__c,
                                    Publisher__c,
                                    Resource_Commitment__c,
                                    Status__c,
                                    Total_Awards__c,
                                    Story__c
                            FROM Activity__c 
                            WHERE Id IN (SELECT Activity__c FROM UserActivityMilestone__c WHERE User__c = :user.Id)]);
        //Getting ACtivities where user is Publisher
        activitiesMap.putAll([SELECT Name,
                                    Activity_Type__c,
                                    Budget_Authorized__c,
                                    Cost__c,
                                    Description__c,
                                    Minimum_Viable_Score__c,
                                    Possible_Score__c,
                                    Publisher__c,
                                    Resource_Commitment__c,
                                    Status__c,
                                    Total_Awards__c,
                                    Story__c
                            FROM Activity__c 
                            WHERE Publisher__c = :user.Id]);
        return activitiesMap.values();

    }
    ////////////////////////////////////////// END Activity \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    
    ////////////////////////////////////////// Milestone \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    
    /**
     * determines the list of milestones for a particular activity
     * @param milestones List of milestones for athe activity
     * @param activity   Activity for which mislestones will be set
     */
    public void setMilestones(List<Milestone__c> milestones, Activity__c activity) {
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for(Milestone__c milestone : milestones)
            activityMilestones.add(new ActivityMilestones__c(Milestone__c = milestone.Id, Activity__c = activity.Id));
        insert activityMilestones;
    }
    /**
     * gets the list of milestones for an activity
     * @param  activity Activity for which mislestones will be returned
     * @return          List<Milestone__c>
     */
    public List<Milestone__c> getMilestones(Activity__c activity) {
        List<ActivityMilestones__c> activityMilestones = [SELECT Milestone__c,
                                                                Milestone__r.Step_Number__c,
                                                                Milestone__r.Name
                                                          FROM ActivityMilestones__c WHERE Activity__c = :activity.Id];
        List<Milestone__c> result = new List<Milestone__c>();
        for(ActivityMilestones__c activityMilestone : activityMilestones)
            result.add(activityMilestone.Milestone__r);
        return result;
    }
    ////////////////////////////////////////// END Milestone \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    ////////////////////////////////////////// ActivitySkill \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    /**
     * adds requested skills to an activity
     * @param skills   List of milestones for the activity
     * @param activity Activity for which Skills will be set
     */
    public void addSkills(List<Skills__c> skills, Activity__c activity) {
        List<ActivitySkills__c> activitySkills = new List<ActivitySkills__c>();
        for (Skills__c skill : skills)
            activitySkills.add(new ActivitySkills__c(Skill__c = skill.Id, Activity__c = activity.Id));
        insert activitySkills;
    }
    /**
     * deletes skills from an activity
     * @param skills   List of milestones for the activity
     * @param activity Activity for which Skills will be deleted
     */
    public void deleteSkills(List<Skills__c> skills, Activity__c activity) {
        Set<Id> skillsIds = new Map<Id, SKills__c>(skills).keySet();
        delete [SELECT Id FROM ActivitySkills__c WHERE Skill__c IN :skillsIds AND Activity__c = :activity.Id];
    }
    /**
     * gets the skills for an activity
     * @param  activity Activity for which Skills will be returned
     * @return          List<Skills__c>
     */
    public List<Skills__c> getSkills(Activity__c activity) {
        
        return [SELECT Id,
                       Name,
                       Experience_Level__c,
                       Internal_Project__c,
                       User__c,
                       Skill__c
                FROM Skills__c WHERE Id IN (SELECT Skill__c FROM ActivitySkills__c WHERE Activity__c = :activity.Id)];
    }
    ////////////////////////////////////////// END ActivitySkill \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    

    ////////////////////////////////////////// Requirement \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    /**
     * get a collection of requirements for an activity
     * @param  activity Activity for which Requirements will be returned
     * @return          List<Requirement__c>
     */
    public List<Requirement__c> getRequirements(Activity__c activity) {
        return [SELECT  Name,
                        Activity__c,
                        Description__c,
                        Requirement_Evaluation__c,
                        Requirement_Weight__c,
                        Type__c
                FROM Requirement__c WHERE Activity__c = :activity.Id];
    }
    /**
     * adds a list of requirements related to a particular activity
     * @param requirements List of Requirements that will be added
     */
    public List<Requirement__c> addRequirements(List<Requirement__c> requirements) {
        //NOTE: Take Activity's Id only from first requirement. We sure that users pass only those requirements that belong to only one activity
        if(isLocked(new Activity__c(Id = requirements[0].Activity__c)))
            throw new ActivityServiceException('Cannot add requirements when activity is locked.');
        insert requirements;
        return requirements;
    }
    /**
     * allows editing of a particular requirements related to an activity
     * @param  requirements List of Requirements that will be updated
     */
    public List<Requirement__c> updateRequirement(List<Requirement__c> requirements) {
        //NOTE: Take Activity's Id only from first requirement. We sure that users pass only those requirements that belong to only one activity
        if(isLocked(new Activity__c(Id = requirements[0].Activity__c)))
            throw new ActivityServiceException('Cannot update requirements when activity is locked.');
        update requirements;
        return requirements;
    }
    /**
     * deletes a list of requirements related to a particular activity
     * @param requirement List of Requirements that will be deleted
     */
    public void deleteRequirements(List<Requirement__c> requirements) {
        //NOTE: Take Activity's Id only from first requirement. We sure that users pass only those requirements that belong to only one activity
        if(isLocked(new Activity__c(Id = requirements[0].Activity__c)))
            throw new ActivityServiceException('Cannot delete requirements when activity is locked.');
        delete requirements;
    }
    ////////////////////////////////////////// END Requirement \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    ////////////////////////////////////////// Award \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    /**
     * adds an award to an activity
     * @param awards List of Awards that will be inserted
     */
    public List<Award__c> addAwards(List<Award__c> awards) {
        insert awards;
        return awards;
    }
    /**
     * updates an award related to an activity
     * @param awards List of Awards that will be updated
     */
    public List<Award__c> updateAwards(List<Award__c> awards) {
        update awards;
        return awards;
    }
    /**
     * deletes an award related to an activity
     * @param awards List of Awards that will be deleted
     */
    public void deleteAwards(List<Award__c> awards) {
        delete awards;
    }
    ////////////////////////////////////////// END Award \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    /**
     * gets the list of default requirements associated with the activity.  Actually to start with, all activities will have the same set of default requirements.
     * @return List<Default_Requirement__c>
     */
    public List<Default_Requirement__c> getDefaultRequirements() {
        return [SELECT Name, Description__c, Requirement_Weight__c, Type__c FROM Default_Requirement__c];
    }
    /**
     * after submission due date we should prevent publishers from adding requirements and members from making submissions.
     * @param  activity Activity to check of lock
     * @return          TRUE if Activity is locked
     */
     
     
    public Boolean isLocked(Activity__c activity) {
    
        /*
        List<ActivityMilestones__c> milestones = [SELECT Milestone__r.Step_Number__c
                FROM ActivityMilestones__c
                WHERE Activity__c = :activity.Id AND Milestone__r.Name LIKE :Constants.SUBMISSION_DATE_MILESTONE_NAME];
        if (milestones.size() == 0)
            throw new ActivityServiceException('Cannot find Submission Date milestone for the provided activity.');
        return milestones[0].Milestone__r.Step_Number__c < Datetime.now();
        */
        
        return false;
    }
    /**
     * deep copy of an Activity along with Awards, Requirements, Skills. After insert all object into database
     * @param  activity Activity to clone
     * @return          New cloned activity
     */
    public Activity__c cloneActivity(Activity__c activity) {
        // Create a savepoint
        Savepoint sp = Database.setSavepoint();
        Activity__c newActivity = null;
        try{
            //Querying old activity with all needed related collections
            Activity__c oldActivity = [SELECT   Name,
                                                Activity_Type__c,
                                                Budget_Authorized__c,
                                                Cost__c,
                                                Description__c,
                                                Minimum_Viable_Score__c,
                                                Possible_Score__c,
                                                Publisher__c,
                                                Resource_Commitment__c,
                                                Status__c,
                                                Total_Awards__c,
                                                Story__c,
                                                (SELECT Activity__c, Milestone__c FROM ActivityMilestones__r),
                                                (SELECT Name, Activity__c, Description__c, Requirement_Evaluation__c, Requirement_Weight__c, Type__c FROM Requirements__r),
                                                (SELECT Activity__c, Payment__c FROM Awards__r)
                                        FROM Activity__c 
                                        WHERE Id = :activity.Id];

            newActivity = oldActivity.clone(false, false, false, false);
            insert newActivity;
            List<sObject> newChildObjects = new List<sObject>();
            //Copying ActivityMilestone objects
            for(ActivityMilestones__c oldActivityMilestone : oldActivity.ActivityMilestones__r){
                ActivityMilestones__c newActivityMilestone = oldActivityMilestone.clone(false, false, false, false);
                newActivityMilestone.Activity__c = newActivity.Id;
                newChildObjects.add(newActivityMilestone);
            }
            //Copying Requirement objects
            for(Requirement__c oldRequirement : oldActivity.Requirements__r){
                Requirement__c newRequirement = oldRequirement.clone(false, false, false, false);
                newRequirement.Activity__c = newActivity.Id;
                newChildObjects.add(newRequirement);
            }
            //Copying Award objects
            for(Award__c oldAward : oldActivity.Awards__r){
                Award__c newAward = oldAward.clone(false, false, false, false);
                newAward.Activity__c = newActivity.Id;
                newChildObjects.add(newAward);
            }
            insert newChildObjects;
        }catch(Exception ex){
            Database.rollback(sp);
            throw ex;
        }
        return newActivity;
    }
    /**
     * Custom Activity Service exception
     */
    public class ActivityServiceException extends ServiceException {

    }
}