src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_CrowdExchange_MemberDashboard.cls
@isTest
private class Test_CrowdExchange_MemberDashboard {

	private static testMethod void testCrowdExchangeMemberDashboard() {
	    
    	//create test data
    	Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createFullActivity(story);
    	TestFactory.createSummaryData();
    	
    	// Start Test  
    	Test.startTest();
    	
    	//Controller instance with standard controller
		CrowdExchange_MemberDashboard crowdExchangeMemberDashboard = new CrowdExchange_MemberDashboard();
    	//System.assert(aaController.account!=null, 'Fail to create Account Record');
    	
    	// Stop Test
    	Test.stopTest();
	}

}