src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityMilestones__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity Milestone</label>
    <nameField>
        <displayFormat>AM-{000000000}</displayFormat>
        <label>ActivityMilestones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Default_Requirement__c.object
<CustomObject>
    <label>Default Requirement</label>
    <nameField>
        <label>Default Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Default Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Evaluation_Percentage__c</fullName>
        <label>Evaluation Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Score__c</fullName>
        <label>Submission Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Timestamp__c</fullName>
        <label>Submission Timestamp</label>
        <type>DateTime</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Submission_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation_Score__c</fullName>
        <label>Evaluation Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Submission Requirements</relationshipLabel>
        <relationshipName>Submission_Requirements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Submission Requirements</relationshipLabel>
        <relationshipName>Submission_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Requirement</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Submission Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UserActivityMilestone__c.object
<CustomObject>
    <fields>
        <fullName>ActivityMilestones__c</fullName>
        <label>ActivityMilestone</label>
        <referenceTo>ActivityMilestones__c</referenceTo>
        <relationshipName>MemberActivityMilestones</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipName>MemberActivites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attachment_ID__c</fullName>
        <description>Stores the Attachment ID for code submissions loaded into SFDC</description>
        <label>Attachment ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MemberActivites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Activity Milestone</label>
    <nameField>
        <displayFormat>UAM-{000000000}</displayFormat>
        <label>UserActivityMilestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Activity Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubmissionServiceTest.cls
@isTest
private class SubmissionServiceTest {
    static ISubmissionService mService = null;
    static ISubmissionService getService() {
        if (mService == null)
            mService = new SubmissionService();
        return mService;
    }

    @isTest static void initializeScorecard_positive() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        Integer dayIndex = 0;
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today().addDays(dayIndex++)));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        insert submission;

        //Start testing
        Test.startTest();
        List<Submission_Requirement__c> result = getService().initializeScorecard(activity, new List<Submission__c> {submission});
        Test.stopTest();

        System.assertEquals(requirements.size(), result.size(), 'Seems like method created wrong number of submission requirements');
        Map<Id, Requirement__c> requirementsMap = new Map<Id, Requirement__c>(requirements);
        for (Submission_Requirement__c submissionRequirement : result) {
            System.assertNotEquals(null, submissionRequirement.Id, 'Seems like requirement was not inserted');
            System.assertEquals(submission.Id, submissionRequirement.Submission__c, 'Requirement has wrong submission reference');
            requirementsMap.remove(submissionRequirement.Requirement__c);
        }
        System.assertEquals(0, requirementsMap.size(), 'Seems like not all requirements were created');
    }

    @isTest static void createSubmission_positive() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today().addDays(1)));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        Attachment attachment = TestFactory.createAttachment();

        //Start testing
        Test.startTest();
        getService().createSubmission(submission, activity, attachment);
        Test.stopTest();
        //Start assertion
        System.assertNotEquals(null, submission.Id, 'Seems like submission was not inserted');
        System.assertNotEquals(null, attachment.Id, 'Seems like attachment was not inserted');
        System.assertEquals(submission.Id, attachment.ParentId, 'Attachment has wrong ParentId. ParentId must equals Submission.Id');
        //List<UserActivityMilestone__c> userActivityMilestones = [SELECT Id FROM UserActivityMilestone__c WHERE Activity__c = :activity.Id AND User__c = :UserInfo.getUserId() AND Attachment_ID__c = :attachment.Id];
        //System.assertEquals(1, userActivityMilestones.size(), 'Cannot find UserActivityMilestone for the submission');
    }
    
    @isTest 
    static void createSubmission_negative_submitAfterDueDate() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today()));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        Attachment attachment = TestFactory.createAttachment();
        Boolean operationFailed = false;

        //Start testing
        Test.startTest();
        try {
            getService().createSubmission(submission, activity, attachment);
        } catch (Exception ex) {
            operationFailed = true;
        }
        Test.stopTest();
        //Start assertion
        System.assert(operationFailed, 'Operation must fail. Cannot create submission after Due Date');

    }
    @isTest static void createSubmission_negative_noMilestones() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        Attachment attachment = TestFactory.createAttachment();
        Boolean operationFailed = false;

        //Start testing
        Test.startTest();
        try {
            getService().createSubmission(submission, activity, attachment);
        } catch (Exception ex) {
            operationFailed = true;
        }
        Test.stopTest();
        //Start assertion
        System.assert(operationFailed, 'Operation must fail. Because Due Date cannot be verified, because there are no ActivityMilestones');

    }
    @isTest static void getValidSubmissions_positive() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today()));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        //VAlid submsiion
        Submission__c submission = TestFactory.createSubmission(activity);
        //Overwritten submission
        Submission__c submission2 = TestFactory.createSubmission(activity);
        submission2.Submission_Timestamp__c = submission2.Submission_Timestamp__c.addMinutes(5);
        //Submission after due date
        Submission__c submission3 = TestFactory.createSubmission(activity);
        submission3.Submission_Timestamp__c = submission3.Submission_Timestamp__c.addDays(20);
        insert new List<Submission__c> {submission, submission2, submission3};

        Test.startTest();
        List<Submission__c> result = getService().getValidSubmissions(activity);
        Test.stopTest();

        System.assertEquals(2, result.size(), 'Seems like method returned wrong number of submissions');
        // TODO: need to fix this figure out why it isn't working....
        System.debug('+++Result[0].Date:' + result[0].Submission_Timestamp__c );
        System.assertEquals(submission2.Id, result[0].Id, 'Seems like method returned wrong submission');
    }

    @isTest static void evaluateRequirement_positive() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today()));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        insert submission;
        Submission_Requirement__c submissionRequirement = TestFactory.createSubmissionRequirement(submission, requirements[0]);
        insert submissionRequirement;
        submissionRequirement.Evaluation_Score__c = 5;

        //Start testing
        Test.startTest();
        getService().evaluateRequirement(new List<Submission_Requirement__c> {submissionRequirement});
        Test.stopTest();

        submissionRequirement = [SELECT Evaluation_Score__c FROM Submission_Requirement__c WHERE Id = :submissionRequirement.Id];
        System.assertEquals(5, submissionRequirement.Evaluation_Score__c, 'Seems like submission requirement was not updated');
    }
    
    // Update test method as per change to calculateSubmissionScore 
    // Updated against TC30050600 
    @isTest static void calculateSubmissionScore_positive() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today()));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        
        Submission__c submission = TestFactory.createSubmission(activity);
        insert submission;
        List<Submission_Requirement__c> submissionRequirements = new List<Submission_Requirement__c>();
        for (Integer i = 0 ; i < requirements.size(); i++) {

            Submission_Requirement__c submissionRequirement = TestFactory.createSubmissionRequirement(submission, requirements[i]);
            submissionRequirement.Evaluation_Score__c = SubmissionService.MAX_SCORE_PER_REQUIREMENT;
            submissionRequirements.add(submissionRequirement);
        }
        //Making one submission requirement unfiled, so score will be MIN
        submissionRequirements[0].Evaluation_Score__c = null;
        insert submissionRequirements;

        //Start testing
        Test.startTest();
        Integer result = getService().calculateSubmissionScore(submission);
        Test.stopTest();
        
        // There are total 12 requirments with Requirement Weight as medium i.e 2 multiple maximum score
        Decimal maxScore = 12 * (SubmissionService.MAX_SCORE_PER_REQUIREMENT * 2);
        
        // There are total 11 Submission_Requirement__c with Evaluation_Score__c as maximum i.e 4 and corresponding requirment 
        // weight as medium i.e 2 Plus one Submission_Requirement__c with minimum score as it Evaluation_Score__c is set to null.
        Decimal evaluationScore = 11 * (SubmissionService.MAX_SCORE_PER_REQUIREMENT * 2) + (SubmissionService.MIN_SCORE_PER_REQUIREMENT * 2);
        
        //Start assertion
        System.assertEquals(evaluationScore, result, 'Method returned wrong points sum');
        submission = [SELECT Submission_Score__c, Evaluation_Percentage__c FROM Submission__c WHERE Id = :submission.Id];
        System.assertEquals(evaluationScore, submission.Submission_Score__c, 'Submition has wrong score');
        System.assertEquals(evaluationScore / (maxScore) * 100, submission.Evaluation_Percentage__c, 'Submition has wrong percentage');
    }

    @isTest static void updateStatus_positive_goToReadyToTest() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today()));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        insert submission;

        //Start testing
        Test.startTest();
        List<Submission__c> result = getService().updateStatus(new List<Submission__c> {submission});
        Test.stopTest();
        //Start assertion
        System.assertEquals(1, result.size(), 'Method returned wrong number of submissions');
        System.assertEquals(Submission.Id, result[0].Id, 'Method returned wrong submission');
        System.assertEquals(Constants.READY_TO_REVIEW_STATUS, result[0].Status__c, 'Method did not changed submission status');
    }
    @isTest static void updateStatus_positive_goToReviewComplete() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today()));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        submission.Status__c = Constants.READY_TO_REVIEW_STATUS;
        insert submission;

        //Start testing
        Test.startTest();
        List<Submission__c> result = getService().updateStatus(new List<Submission__c> {submission});
        Test.stopTest();
        //Start assertion
        System.assertEquals(1, result.size(), 'Method returned wrong number of submissions');
        System.assertEquals(submission.Id, result[0].Id, 'Method returned wrong submission');
        System.assertEquals(Constants.REVIEW_COMPLETE_STATUS, result[0].Status__c, 'Method did not changed submission status');
    }
    @isTest static void getSubmissionsForUser_positive() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today()));
        insert activityMilestones;
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        insert submission;

        //Start testing
        Test.startTest();
        List<Submission__c> result = getService().getSubmissionsForUser(new User(Id = UserInfo.getUserId()));
        Test.stopTest();

        System.assertEquals(1, result.size(), 'Method returned wrong number of submissions');
        System.assertEquals(submission.Id, result[0].Id, 'Method returned wrong submission');
    }

    @isTest static void uploadFile_positive() {
        //Init test data
        Story__c story = TestFactory.createStory();
        insert story;
        Activity__c activity = TestFactory.createActivity(story);
        insert activity;
        List<Default_Requirement__c> defaultRequirements = TestFactory.createDefaultRequirements();
        insert defaultRequirements;
        List<Requirement__c> requirements = new List<Requirement__c>();
        //Creating milestones
        List<Milestone__c> milestones = TestFactory.createDefaultMilestones();
        insert milestones;
        List<ActivityMilestones__c> activityMilestones = new List<ActivityMilestones__c>();
        for (Milestone__c milestone : milestones)
            activityMilestones.add(TestFactory.createActivityMilestone(activity, milestone, Date.today()));
        insert activityMilestones;
       
        //Creating default requirements
        for (Default_Requirement__c defaultRequirement : defaultRequirements)
            requirements.add(TestFactory.createRequirement(activity, defaultRequirement));
        insert requirements;
        Submission__c submission = TestFactory.createSubmission(activity);
        insert submission;
        Attachment attachment = TestFactory.createAttachment();

        //Start testing
        Test.startTest();
        Attachment result = getService().uploadFile(attachment, submission);
        Test.stopTest();
        //Start assertion
        System.assertNotEquals(null, attachment.Id, 'Seems like attacment was not inserted');
        System.assertEquals(submission.Id, attachment.ParentId, 'Attachment must belong to the passed submission.');
        
      
    }

}