src/objects/CE_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Member__c</fullName>
        <label>Assigned Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities_User_Assigned_To</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_Story__c</fullName>
        <label>Story</label>
        <referenceTo>CE_Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Skills__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CE_Story__c.object
<CustomObject>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CE_User_Header_Picture__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Header_Pictures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Header Picture</label>
    <nameField>
        <displayFormat>UHP-{00000000}</displayFormat>
        <label>User Header Picture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Header Pictures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CE_UserSkill__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>CE_Skills__c</referenceTo>
        <relationshipLabel>User Skills</relationshipLabel>
        <relationshipName>User_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Skill</label>
    <nameField>
        <displayFormat>US-{000000000}</displayFormat>
        <label>UserSkill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Crowd_Exchange_User_Type__c</fullName>
        <label>Crowd_Exchange_User_Type</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publisher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/CE_Test_MemPubProfileController.cls
@isTest
private class CE_Test_MemPubProfileController {
    
    // Creat Test Data
    public static void createTestData(){

        // Create Publisher user
    	  User user = CE_TestFactory.createUser();
    	  user.Crowd_Exchange_User_Type__c = 'Publisher';
        insert user;
        
        //Create Story record
        List<CE_Story__c> listStory = new List<CE_Story__c>();
    	  CE_Story__c story = CE_TestFactory.createStory();
    	  story.Publisher__c = userinfo.getuserId();
        listStory.add(story);
        
        //Create Story record
    	  CE_Story__c story1 = CE_TestFactory.createStory();
     	  story.Publisher__c = userinfo.getuserId();
    	  story.Status__c = 'Completed';
        listStory.add(story1);
        insert listStory;
        
        //Create Activities 
        List<CE_Activity__c> listActivity = new List<CE_Activity__c>();
        CE_Activity__c activity1 = CE_TestFactory.createActivity(story);
        activity1.Status__c = 'Completed';
        activity1.Publisher__c = userinfo.getuserId();
        activity1.Assigned_Member__c = userinfo.getuserId();
        listActivity.add(activity1);
        
        CE_Activity__c activity2 = CE_TestFactory.createActivity(story);
        activity2.Status__c = 'In Submission';
        activity2.Assigned_Member__c = user.Id;
        activity2.Publisher__c = userinfo.getuserId();
        listActivity.add(activity2);
        
        CE_Activity__c activity3 = CE_TestFactory.createActivity(story1);
        activity3.Status__c = 'In Submission';
        activity3.Assigned_Member__c = user.Id;
        activity3.Publisher__c = userinfo.getuserId();
        listActivity.add(activity3);
        
        insert listActivity;
        
        //Create Header Picture
        CE_User_Header_Picture__c userHeaderPicture = new CE_User_Header_Picture__c();
        userHeaderPicture.User__c = userinfo.getuserId();
        insert userHeaderPicture;
        
         
        //Create Summary Data
    	  CE_TestFactory.createSummaryData();
    }
    
    /*
        Test method with Test Data
    */
	private static testMethod void testCrowdExchangeMemPubProfile(){
	    
        //Create test Data
        createTestData();
        
    	// Start Test  
    	Test.startTest();
    	
    	//Controller instance
		CE_MemPubProfileController crowdExchangeMemPubProfile = new CE_MemPubProfileController();
		
		// System Asserts
    	System.assert(crowdExchangeMemPubProfile.isActiveStoriesPresent == true,'Active Story present');
    	System.assert(crowdExchangeMemPubProfile.isCompletedStoriesPresent == true,'Completed Story present');
    	
    	// Stop Test
    	Test.stopTest();
	}
	
	/*
        Test methods without Test Data
    */
	private static testMethod void testCrowdExchangeMemPubProfile_NoData(){

    	// Start Test  
    	Test.startTest();
    	
    	//Controller instance
		CE_MemPubProfileController crowdExchangeMemPubProfile = new CE_MemPubProfileController();
		          
		// System Asserts
    	System.assert(crowdExchangeMemPubProfile.isActiveStoriesPresent == false,'Active Story not present');          
    	System.assert(crowdExchangeMemPubProfile.isCompletedStoriesPresent == false,'Completed Story not present');
    	
    	// Stop Test
    	Test.stopTest();
	}
	
	/*
        Test Remote Action Method to update user information
    */
	private static testMethod void testUserInformationUpdateRemoteAction(){

    	// Start Test  
    	Test.startTest();
    	
    	//Create Skill and Use Skill
        CE_Skills__c skill = CE_TestFactory.createSkill('Test Awesome Skill');
        insert skill;
        List<CE_UserSkill__c> listUserSkill = new List<CE_UserSkill__c>();
        CE_UserSkill__c userSkill = new CE_UserSkill__c(Member__c = userinfo.getuserId(), Skill__c = skill.Id);
        listUserSkill.add(userSkill);
        
        CE_UserSkill__c userSkill1 = new CE_UserSkill__c(Member__c = userinfo.getuserId(), Skill__c = skill.Id);
        listUserSkill.add(userSkill1);
        insert listUserSkill;
    	
    	//Controller instance
		Boolean result = CE_MemPubProfileController.uploadProfilePicture(userinfo.getuserId(),false,'','',true,'abc.jpg','aaa','fName','lName','email','role','organization','123456','aboutMe');
        // System Asserts
    	System.assert(result == false,'User Information update not Successful');
    	
    	// Stop Test
    	Test.stopTest();
	}

	/*   
        Test Remote Action Method to update user information with pic changed
    */
	private static testMethod void testUserInformationUpdateRemoteAction_PicChanged(){

    	// Start Test  
    	Test.startTest();
    	
    	//Create Skill and Use Skill
        CE_Skills__c skill = CE_TestFactory.createSkill('Test Awesome Skill');
        insert skill;
        List<CE_UserSkill__c> listUserSkill = new List<CE_UserSkill__c>();
        CE_UserSkill__c userSkill = new CE_UserSkill__c(Member__c = userinfo.getuserId(), Skill__c = skill.Id);
        listUserSkill.add(userSkill);
        
        CE_UserSkill__c userSkill1 = new CE_UserSkill__c(Member__c = userinfo.getuserId(), Skill__c = skill.Id);
        listUserSkill.add(userSkill1);
        insert listUserSkill;
        
        //Create Header Picture
        CE_User_Header_Picture__c userHeaderPicture = new CE_User_Header_Picture__c();
        userHeaderPicture.User__c = userinfo.getuserId();
        insert userHeaderPicture;
        

    	//Controller instance
		Boolean result = CE_MemPubProfileController.uploadProfilePicture(userinfo.getuserId(),false,'test.jpg','test',true,'test.jpg','test','fName','lName','email','role','organization','123456','aboutMe');
        // System Asserts
    	System.assert(result == false,'User Information update not Successful');
    	
    	
    	// Stop Test
    	Test.stopTest();
	}
	
	/*
        Test Remote Action Method to update user information with Picture already present and pic changed
    */
	private static testMethod void testUserInformationUpdateRemoteAction_WithPicture(){

    	// Start Test  
    	Test.startTest();
    	
    	//Create Skill and Use Skill
        CE_Skills__c skill = CE_TestFactory.createSkill('Test Awesome Skill');
        insert skill;
        List<CE_UserSkill__c> listUserSkill = new List<CE_UserSkill__c>();
        CE_UserSkill__c userSkill = new CE_UserSkill__c(Member__c = userinfo.getuserId(), Skill__c = skill.Id);
        listUserSkill.add(userSkill);
        
        CE_UserSkill__c userSkill1 = new CE_UserSkill__c(Member__c = userinfo.getuserId(), Skill__c = skill.Id);
        listUserSkill.add(userSkill1);
        insert listUserSkill;
    	
    	//Create Header Picture
        CE_User_Header_Picture__c userHeaderPicture = new CE_User_Header_Picture__c();
        userHeaderPicture.User__c = userinfo.getuserId();
        insert userHeaderPicture;
        
        //Controller instance
		Boolean result = CE_MemPubProfileController.uploadProfilePicture(userinfo.getuserId(),true,'test.jpg','test',true,'test.jpg','test','fName','lName','email','role','organization','123456','aboutMe');
        // System Asserts
    	System.assert(result == false,'User Information update not Successful');
    	
    	// Stop Test
    	Test.stopTest();
	}
	

}