src/objects/CE_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Member__c</fullName>
        <label>Assigned Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities_User_Assigned_To</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Authorized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget Authorized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Challenge_Type__c</fullName>
        <label>Challenge Type</label>
        <picklist>
            <picklistValues>
                <fullName>Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Member_Assigned__c</fullName>
        <label>Date Member Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Minimum_Viable_Score__c</fullName>
        <label>Minimum Viable Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Possible_Score__c</fullName>
        <label>Possible Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Commitment__c</fullName>
        <description>% of utilization required/expected (e.g. 25%)</description>
        <inlineHelpText>% of utilization required/expected (e.g. 25%)</inlineHelpText>
        <label>Resource Commitment</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_Story__c</fullName>
        <label>Story</label>
        <referenceTo>CE_Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Awards__c</fullName>
        <label>Total Awards</label>
        <summarizedField>CE_Award__c.Payment__c</summarizedField>
        <summaryForeignKey>CE_Award__c.CE_Activity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>hasAwards__c</fullName>
        <defaultValue>false</defaultValue>
        <label>hasAwards</label>
        <type>Checkbox</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_ActivityMilestones__c.object
<CustomObject>
    <fields>
        <fullName>CE_Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>CE_Activity__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CE_Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>CE_Milestone__c</referenceTo>
        <relationshipName>ActivityMilestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scheduled_Date__c</fullName>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <label>Activity Milestone</label>
    <nameField>
        <displayFormat>AM-{000000000}</displayFormat>
        <label>ActivityMilestones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_ActivitySkills__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Skill__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Field holding concatenated Activity Id and the Skill Id to create a synthetic id to prevent adding duplicate Activity and Skill combinations to ActivitySkill table</description>
        <externalId>true</externalId>
        <inlineHelpText>Field holding concatenated Activity Id and the Skill Id to create a synthetic id to prevent adding duplicate Activity and Skill combinations to ActivitySkill table</inlineHelpText>
        <label>Activity Skill</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CE_Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>CE_Activity__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>CE_Skills__c</referenceTo>
        <relationshipLabel>Activity Skills</relationshipLabel>
        <relationshipName>Activity_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Skill</label>
    <nameField>
        <displayFormat>AS-{0000000000}</displayFormat>
        <label>Activity Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Award__c.object
<CustomObject>
    <fields>
        <fullName>CE_Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>CE_Activity__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Place__c</fullName>
        <label>Place</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Award</label>
    <nameField>
        <displayFormat>Award-{000000000}</displayFormat>
        <label>Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Step_Number__c</fullName>
        <label>Step Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Software Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CE_Registration__c.object
<CustomObject>
    <fields>
        <fullName>CE_Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>CE_Activity__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>CE_Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>CE_Activity__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Parent_Requirement__c</fullName>
        <label>Parent Requirement</label>
        <referenceTo>CE_Requirement__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement_Evaluation__c</fullName>
        <label>Requirement Evaluation</label>
        <picklist>
            <picklistValues>
                <fullName>Meets requirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Somewhat satisfies requirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does not meet requirement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requirement_Number__c</fullName>
        <label>Requirement Number</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirement_Weight__c</fullName>
        <description>Importance of a particular requirement</description>
        <inlineHelpText>Importance of a particular requirement</inlineHelpText>
        <label>Requirement Weight</label>
        <picklist>
            <picklistValues>
                <fullName>Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Application Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Story__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CE_ActivityService.cls
public with sharing class CE_ActivityService implements CE_IActivityService {

    ////////////////////////////////////////// Activity \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    /**
     * creates activities
     * @param  activities list of activities to insert
     * @return            created list of activies with ids
     */
    public List<CE_Activity__c> createActivities(List<CE_Activity__c> activities) {
        insert activities;
        return activities;
    }
    /**
     * updates activities
     * @param  activities list of activities to insert
     * @return            updated list of activies
     */
    public List<CE_Activity__c> updateActivities(List<CE_Activity__c> activities) {
        update activities;
        return activities;
    }
    
    /**
     * create single activity
     * Updated against TC30050600
     * @param  activity     activity record to insert
     * @return            created activity record with id
     */
    public CE_Activity__c createActivity(CE_Activity__c activity) {
        insert activity;
        return activity;
    }
    
    /**
     * update single activity
     * Updated against TC30050600
     * @param  activity activity record to update
     * @return      updated activity
     */
    public CE_Activity__c updateActivity(CE_Activity__c activity) {
        update activity;
        return activity; 
    }
    
    /**
     * deletes activities
     * @param activities list of activities to delete
     */
    public void deleteActivities(List<CE_Activity__c> activities) {
        delete activities;
    }
    /**
     * searches for activities based on a list of skills
     * @param  skills list of skills for Activities' filter
     * @return        List<CE_Activity__c> 
     */
    public List<CE_Activity__c> search(List<CE_Skills__c> skills) {
        Set<Id> skillsIds = new Map<Id,CE_Skills__c>(skills).keySet();
        return [SELECT Name,
                        Challenge_Type__c,
                        Budget_Authorized__c,
                        Cost__c,
                        Description__c,
                        Minimum_Viable_Score__c,
                        Possible_Score__c,
                        Publisher__c,
                        Resource_Commitment__c,
                        Status__c,
                        Total_Awards__c,
                        CE_Story__c
                FROM CE_Activity__c 
                WHERE Id IN (SELECT CE_Activity__c FROM CE_ActivitySkills__c WHERE Skill__c IN :skillsIds)];
    }
    
     /**
     * method to assign member to activity  
     * Updated against TC30050600
     * @param user User to be assigned to activity
     * @param activity   Activity to which member will be assigned.
     */
    public void assignMemberToActivity(User user, CE_Activity__c activity) {
        activity.Assigned_Member__c = user.Id;
        activity.Date_Member_Assigned__c = DateTime.now();
        update activity;
    }
    
    /**
     * gets a collections of activities associated with a particular user.  The user might be a publisher or a member.
     * @param  user User record(member or publisher)
     * @return      List<CE_Activity__c>
     */
    public List<CE_Activity__c> getActivitiesForUser(User user) {
        Map<Id, CE_Activity__c> activitiesMap = new Map<Id, CE_Activity__c>();
       
        //Getting activities where user be a Member or publisher
        //Updated against TC30050600
        activitiesMap.putAll([SELECT Name,
                                    Challenge_Type__c,
                                    Budget_Authorized__c,
                                    Cost__c,
                                    Description__c,
                                    Minimum_Viable_Score__c,
                                    Possible_Score__c,
                                    Publisher__c,
                                    Resource_Commitment__c,
                                    Status__c,
                                    Total_Awards__c,
                                    Assigned_Member__c,
                                    Date_Member_Assigned__c,
                                    CE_Story__c
                            FROM CE_Activity__c 
                            WHERE Assigned_Member__c = :user.Id OR Publisher__c = :user.Id ]);
        
        return activitiesMap.values();
    }
    
    /**
     * get activity associated with assigned member and Date Member Assigned.
     * Updated against TC30050600   #7
     * @param  activityId Activity Id
     * @return      CE_Activity__c
     */
    public CE_Activity__c getActivity(Id activityId) {
        return [SELECT  Name,
                        Challenge_Type__c,
                        Budget_Authorized__c,
                        Cost__c,
                        Description__c,
                        Minimum_Viable_Score__c,
                        Possible_Score__c,
                        Publisher__c,
                        Resource_Commitment__c,
                        Status__c,
                        Total_Awards__c,
                        Assigned_Member__c,
                        Date_Member_Assigned__c,
                        CE_Story__c
                FROM CE_Activity__c 
                WHERE Id =: activityId];
        
    }
    ////////////////////////////////////////// END Activity \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    
    ////////////////////////////////////////// Milestone \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    
    /**
     * determines the list of milestones for a particular activity
     * @param milestones List of milestones for athe activity
     * @param activity   Activity for which mislestones will be set
     */
    public void setMilestones(List<CE_Milestone__c> milestones, CE_Activity__c activity) {
        List<CE_ActivityMilestones__c> activityMilestones = new List<CE_ActivityMilestones__c>();
        for(CE_Milestone__c milestone : milestones)
            activityMilestones.add(new CE_ActivityMilestones__c(CE_Milestone__c = milestone.Id, CE_Activity__c = activity.Id));
        insert activityMilestones;
    }
    /**
     * gets the list of milestones for an activity
     * @param  activity Activity for which mislestones will be returned
     * @return          List<CE_Milestone__c>
     */
    public List<CE_Milestone__c> getMilestones(CE_Activity__c activity) {
        List<CE_ActivityMilestones__c> activityMilestones = [SELECT CE_Milestone__c,
                                                                CE_Milestone__r.Step_Number__c,
                                                                CE_Milestone__r.Name
                                                          FROM CE_ActivityMilestones__c WHERE CE_Activity__c = :activity.Id];
        List<CE_Milestone__c> result = new List<CE_Milestone__c>();
        for(CE_ActivityMilestones__c activityMilestone : activityMilestones)
            result.add(activityMilestone.CE_Milestone__r);
        return result;
    }
    ////////////////////////////////////////// END Milestone \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    ////////////////////////////////////////// ActivitySkill \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    /**
     * adds requested skills to an activity
     * @param skills   List of milestones for the activity
     * @param activity Activity for which Skills will be set
     */
    public void addSkills(List<CE_Skills__c> skills, CE_Activity__c activity) {
        List<CE_ActivitySkills__c> activitySkills = new List<CE_ActivitySkills__c>();
        for (CE_Skills__c skill : skills) {
            // Updated against TC30050600 
            String activitySkillId = activity.Id + '' + skill.Id;
            activitySkills.add(new CE_ActivitySkills__c(Skill__c = skill.Id, CE_Activity__c = activity.Id, Activity_Skill__c = activitySkillId));
        }
        upsert activitySkills;
    }
    /**
     * deletes skills from an activity
     * @param skills   List of milestones for the activity
     * @param activity Activity for which Skills will be deleted
     */
    public void deleteSkills(List<CE_Skills__c> skills, CE_Activity__c activity) {
        Set<Id> skillsIds = new Map<Id, CE_Skills__c>(skills).keySet();
        delete [SELECT Id FROM CE_ActivitySkills__c WHERE Skill__c IN :skillsIds AND CE_Activity__c = :activity.Id];
    }
    /**
     * gets the skills for an activity
     * @param  activity Activity for which Skills will be returned
     * @return          List<CE_Skills__c>
     */
    public List<CE_Skills__c> getSkills(CE_Activity__c activity) {
        
        return [SELECT Id,
                       Name 
                FROM CE_Skills__c WHERE Id IN (SELECT Skill__c FROM CE_ActivitySkills__c WHERE CE_Activity__c = :activity.Id)];
    }
    ////////////////////////////////////////// END ActivitySkill \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    

    ////////////////////////////////////////// Requirement \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    /**
     * get a collection of requirements for an activity
     * @param  activity Activity for which Requirements will be returned
     * @return          List<CE_Requirement__c>
     */
    public List<CE_Requirement__c> getRequirements(CE_Activity__c activity) {
        return [SELECT  Name,
                        CE_Activity__c,
                        Description__c,
                        Requirement_Evaluation__c,
                        Requirement_Weight__c,
                        Type__c
                FROM CE_Requirement__c WHERE CE_Activity__c = :activity.Id];
    }
    /**
     * adds a list of requirements related to a particular activity
     * @param requirements List of Requirements that will be added
     */
    public List<CE_Requirement__c> addRequirements(List<CE_Requirement__c> requirements) {
        //NOTE: Take Activity's Id only from first requirement. We sure that users pass only those requirements that belong to only one activity
        if(isLocked(new CE_Activity__c(Id = requirements[0].CE_Activity__c)))
            throw new ActivityServiceException('Cannot add requirements when activity is locked.');
        insert requirements;
        return requirements;
    }
    /**
     * allows editing of a particular requirements related to an activity
     * @param  requirements List of Requirements that will be updated
     */
    public List<CE_Requirement__c> updateRequirement(List<CE_Requirement__c> requirements) {
        //NOTE: Take Activity's Id only from first requirement. We sure that users pass only those requirements that belong to only one activity
        if(isLocked(new CE_Activity__c(Id = requirements[0].CE_Activity__c)))
            throw new ActivityServiceException('Cannot update requirements when activity is locked.');
        update requirements;
        return requirements;
    }
    /**
     * deletes a list of requirements related to a particular activity
     * @param requirement List of Requirements that will be deleted
     */
    public void deleteRequirements(List<CE_Requirement__c> requirements) {
        //NOTE: Take Activity's Id only from first requirement. We sure that users pass only those requirements that belong to only one activity
        if(isLocked(new CE_Activity__c(Id = requirements[0].CE_Activity__c)))
            throw new ActivityServiceException('Cannot delete requirements when activity is locked.');
        delete requirements;
    }
    ////////////////////////////////////////// END Requirement \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    ////////////////////////////////////////// Award \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    /**
     * adds an award to an activity
     * @param awards List of Awards that will be inserted
     */
    public List<CE_Award__c> addAwards(List<CE_Award__c> awards) {
        insert awards;
        return awards;
    }
    /**
     * updates an award related to an activity
     * @param awards List of Awards that will be updated
     */
    public List<CE_Award__c> updateAwards(List<CE_Award__c> awards) {
        update awards;
        return awards;
    }
    /**
     * deletes an award related to an activity
     * @param awards List of Awards that will be deleted
     */
    public void deleteAwards(List<CE_Award__c> awards) {
        delete awards;
    }
    ////////////////////////////////////////// END Award \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    /**
     * gets the list of default requirements associated with the activity.  Actually to start with, all activities will have the same set of default requirements.
     * @return List<CE_Default_Requirement__c>
     */
    public List<CE_Default_Requirement__c> getDefaultRequirements() {
        return [SELECT Name, Description__c, Requirement_Weight__c, Type__c FROM CE_Default_Requirement__c];
    }
    
    
    /**
     * after submission due date we should prevent publishers from adding requirements and members from making submissions.
     * Updated against TC30050600 
     * @param  activity Activity to check of lock
     * @return          TRUE if Activity is locked
     */
    public Boolean isLocked(CE_Activity__c activity) {
    
        
        List<CE_ActivityMilestones__c> milestones = [SELECT CE_Milestone__r.Step_Number__c, Scheduled_Date__c
               FROM CE_ActivityMilestones__c
               WHERE CE_Activity__c = :activity.Id AND CE_Milestone__r.Name LIKE :CE_Constants.SUBMISSION_DATE_MILESTONE_NAME];
        if (milestones.size() == 0)
            throw new ActivityServiceException('Cannot find Submission Date milestone for the provided activity.');
        
        return milestones[0].Scheduled_Date__c < Datetime.now();
        
    }
    
    /**
     * deep copy of an Activity along with Awards, Requirements, Skills. After insert all object into database
     * @param  activity Activity to clone
     * @return          New cloned activity
     */
    public CE_Activity__c cloneActivity(CE_Activity__c activity) {
        // Create a savepoint
        Savepoint sp = Database.setSavepoint();
        CE_Activity__c newActivity = null;
        try{
            //Querying old activity with all needed related collections
            CE_Activity__c oldActivity = [SELECT   Name,
                                                Challenge_Type__c,
                                                Budget_Authorized__c,
                                                Cost__c,
                                                Description__c,
                                                Minimum_Viable_Score__c,
                                                Possible_Score__c,
                                                Publisher__c,
                                                Resource_Commitment__c,
                                                Status__c,
                                                Total_Awards__c,
                                                CE_Story__c,
                                                hasAwards__c,
                                                (SELECT CE_Activity__c, CE_Milestone__c FROM ActivityMilestones__r),
                                                (SELECT Name, CE_Activity__c, Description__c, Requirement_Evaluation__c, Requirement_Weight__c, Type__c, Requirement_Number__c, Parent_Requirement__c FROM Requirements__r),
                                                (SELECT Place__c, CE_Activity__c, Payment__c FROM Awards__r)
                                        FROM CE_Activity__c 
                                        WHERE Id = :activity.Id];

            newActivity = oldActivity.clone(false, false, false, false);
            insert newActivity;
            List<sObject> newChildObjects = new List<sObject>();
            //Copying ActivityMilestone objects
            for(CE_ActivityMilestones__c oldActivityMilestone : oldActivity.ActivityMilestones__r){
                CE_ActivityMilestones__c newActivityMilestone = oldActivityMilestone.clone(false, false, false, false);
                newActivityMilestone.CE_Activity__c = newActivity.Id;
                newChildObjects.add(newActivityMilestone);
            }
            //Copying Requirement objects
            for(CE_Requirement__c oldRequirement : oldActivity.Requirements__r){
                CE_Requirement__c newRequirement = oldRequirement.clone(false, false, false, false);
                newRequirement.CE_Activity__c = newActivity.Id;
                newChildObjects.add(newRequirement);
            }
            //Copying Award objects
            for(CE_Award__c oldAward : oldActivity.Awards__r){
                CE_Award__c newAward = oldAward.clone(false, false, false, false);
                newAward.CE_Activity__c = newActivity.Id;
                newChildObjects.add(newAward);
            }
            insert newChildObjects;
        }catch(Exception ex){
            Database.rollback(sp);
            throw ex;
        }
        return newActivity;
    }
    
    /*
    * Method for registering a member to an activity.
    * Added against TC30050600 
    * @param  userId User Id
    * @param  activity Activity for which Registration will be inserted
    * @return          List<CE_Registration__c>
    */
    public void registerMember(Id userId, CE_Activity__c activity) {
        CE_Registration__c registerMember = new CE_Registration__c(
                CE_Activity__c = activity.Id, 
                User__c = userId, 
                Registration_Date__c = DateTime.now());
        insert registerMember;              
    }
    
    /*
    *   Get list of the members that are registered to a particular activity.
    *   Added against TC30050600 
    * @param  activity Activity for which Registration will be returned
    * @return          List<CE_Registration__c>
    */
    public List<CE_Registration__c> getRegistrations(CE_Activity__c activity) {
        return [SELECT  Name,
                        CE_Activity__c,
                        Registration_Date__c,
                        User__c,
                        User__r.Name,
                        User__r.FirstName,
                        User__r.LastName,
                        User__r.SmallPhotoUrl
                FROM CE_Registration__c WHERE CE_Activity__c = :activity.Id];
    }
    
    /*
    * Deregistering a member by deleting the related registration record.
    * Added against TC30050600
    * @Param  registrationId    registeration record id
    */
    public void deregisterMember(Id registrationId) {
        delete [SELECT Id FROM CE_Registration__c WHERE Id =: registrationId];
    }
    
    /**
     * Custom Activity Service exception
     */
    public class ActivityServiceException extends CE_ServiceException {

    }
}