src/objects/CE_Activity__c.object
<CustomObject>
    <fields>
        <fullName>CE_Story__c</fullName>
        <label>Story</label>
        <referenceTo>CE_Story__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CE_Story__c.object
<CustomObject>
    <label>Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CE_Test_MemberDashboardController.cls
@isTest
private class CE_Test_MemberDashboardController {

	private static testMethod void testCrowdExchangeMemberDashboard() {
	    
    	//create test data
    	CE_Story__c story = CE_TestFactory.createStory();
        insert story;
        CE_Activity__c activity = CE_TestFactory.createFullActivity(story);
    	CE_TestFactory.createSummaryData();
    	
    	// Start Test  
    	Test.startTest();
    	
    	//Controller instance with standard controller
		CE_MemberDashboardController crowdExchangeMemberDashboard = new CE_MemberDashboardController();
    	//System.assert(aaController.account!=null, 'Fail to create Account Record');
    	
    	// Stop Test
    	Test.stopTest();
	}

}