src/objects/CE_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Default_Time_Period__c</fullName>
        <description>The default duration in days for a particular activity phase.</description>
        <label>Default Time Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_In_Initial_Setup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether milestone dates will be populated by publishers during initial setup.</description>
        <label>Display In Initial Setup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Step_Number__c</fullName>
        <label>Step Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Crowd_Exchange_User_Type__c</fullName>
        <label>Crowd_Exchange_User_Type</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publisher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/CE_WebApp_ConfigController.cls
public with sharing class CE_WebApp_ConfigController {
	public CE_WebApp_ConfigController() {
		User usr = [SELECT FirstName,LastName, SmallPhotoUrl, FullPhotoUrl, Crowd_Exchange_User_Type__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        currentUser = new CE_WebAppModels.UserModel(usr);

        List<CE_Milestone__c> milestones = [SELECT Name, Display_In_Initial_Setup__c,Default_Time_Period__c,Step_Number__c FROM CE_Milestone__c Order By Step_Number__c];
        List<CE_WebAppModels.MilestoneInfo> milestonesInfo = new List<CE_WebAppModels.MilestoneInfo>();
        for(CE_Milestone__c milestone : milestones){
            milestonesInfo.add(new CE_WebAppModels.MilestoneInfo(milestone));
        }
        this.milestones = JSON.serialize(milestonesInfo);
	}
    public String milestones {get;set;}
    public CE_WebAppModels.UserModel currentUser {get;set;}


}