src/objects/Member_Skill_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Member_Count__c</fullName>
        <label>Member Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill_Name__c</fullName>
        <label>Skill Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <label>Timestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Member Skill Snapshot</label>
    <nameField>
        <label>Skill Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Skill Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Summary_Data__c.object
<CustomObject>
    <fields>
        <fullName>Active_Activities__c</fullName>
        <label>Active Activities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active_Stories__c</fullName>
        <label>Active Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completed_Activities__c</fullName>
        <label>Completed Activities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completed_Stories__c</fullName>
        <label>Completed Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Members__c</fullName>
        <label>Number of Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Publishers__c</fullName>
        <label>Number of Publishers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <label>Timestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Activities__c</fullName>
        <label>Total Activities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Registrations__c</fullName>
        <label>Total Registrations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Reviews__c</fullName>
        <label>Total Reviews</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Stories__c</fullName>
        <label>Total Stories</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Submissions__c</fullName>
        <label>Total Submissions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Users__c</fullName>
        <label>Total Users</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Summary Data</label>
    <nameField>
        <label>Dashboard Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Summary Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DashboardUpdater.cls
/************************************************** 
* Dashboard Updater
* -------------------------------------------------
* Created By: Daniel Eagle (daniel.eagle@hp.com)
* Last Modified: 7/16/2015
* -------------------------------------------------
* Updates the dashboard data.
**************************************************/

global class DashboardUpdater
{
    global void execute() { 
        // variables to hold summary data
        Summary_Data__c summaryData;
        List<Summary_Data__c> summaryDataList = [SELECT Id FROM Summary_Data__c LIMIT 1];
        
        // If summary data exists, assign object in list to summary data object otherwise
        // create new object.
        if (!summaryDataList.isEmpty())
            summaryData = summaryDataList.get(0);
        else
            summaryData = new Summary_Data__c();
        
        // invoke Dashboard Data Collector
        DashboardDataCollector dashboardDataCollector = new DashboardDataCollector(); 
        
        // populate summary data object
        summaryData.Total_Users__c = dashboardDataCollector.getActiveUserTotal();
        summaryData.Total_Activities__c = dashboardDataCollector.getActivityTotal();
        summaryData.Active_Activities__c = dashboardDataCollector.getActiveActivityTotal();
        summaryData.Completed_Activities__c = dashboardDataCollector.getCompletedActivityTotal();
        summaryData.Total_Stories__c = dashboardDataCollector.getStoryTotal();
        summaryData.Active_Stories__c = dashboardDataCollector.getActiveStoryTotal();
        summaryData.Completed_Stories__c = dashboardDataCollector.getCompletedStoryTotal();
        summaryData.Number_of_Members__c = dashboardDataCollector.getMemberTotal();
        summaryData.Number_of_Publishers__c = dashboardDataCollector.getPublisherTotal();
        summaryData.Total_Registrations__c = dashboardDataCollector.getRegistrationTotal();
        summaryData.Total_Reviews__c = dashboardDataCollector.getReviewTotal();
        summaryData.Total_Submissions__c = dashboardDataCollector.getSubmissionTotal();
        summaryData.Timestamp__c = DateTime.now();
        
        // insert into or update database
        upsert summaryData;
        
        // map to hold top skills
        Map<String, Integer> topSkills = dashboardDataCollector.getTopUserSkills();
        
        // list to hold member skill snapshot data
        List<Member_Skill_Snapshot__c> memberSkillSnapshots = [SELECT Id FROM Member_Skill_Snapshot__C];
        
        if (!memberSkillSnapshots.isEmpty()) {
        	// delete existing member skill snapshot data
        	delete memberSkillSnapshots;
        	
        	// clear member skill snapshot list
        	memberSkillSnapshots.clear();
        }
        
        // loop through map and build list
        for (String skillName : topSkills.keySet()) {
        	Member_Skill_Snapshot__c memberSkillSnapshot = new Member_Skill_Snapshot__c();
        	memberSkillSnapshot.Skill_Name__c = skillName;
        	memberSkillSnapshot.Member_Count__c = topSkills.get(skillName);
        	memberSkillSnapshot.Timestamp__c = DateTime.now();
        	memberSkillSnapshots.add(memberSkillSnapshot);
        }
        
        // insert into database
        insert memberSkillSnapshots;
    }
}