src/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Date_Sent__c</fullName>
        <label>Date Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FromUser__c</fullName>
        <label>From User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification_Text__c</fullName>
        <label>Notification Text</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Value 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Notification__c</fullName>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>User Notifications</relationshipLabel>
        <relationshipName>NotificationRecipients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Recipient</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserNotifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Notification</label>
    <nameField>
        <displayFormat>UN-{00000000}</displayFormat>
        <label>User Notification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NotificationEmailHandlerTest.cls
@isTest
private class NotificationEmailHandlerTest {

    /*
		test handleInboundEmail
	*/
    static testMethod void handleInboundEmail_Test() {
        NotificationEmailHandler handler = new NotificationEmailHandler();
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        User fromUser = [SELECT Id, Email FROM User WHERE Id = :UserInfo.getUserId()];
        User toUser = TestFactory.createUser();
        insert toUser;
        
        email.fromAddress = fromUser.Email;
        email.toAddresses = new String[]{toUser.Email};
        email.plainTextBody = 'Plain Text';
        email.subject = 'Subject';
        Messaging.InboundEmail.Header emailTemplate = new Messaging.InboundEmail.Header();
        email.headers = new Messaging.InboundEmail.Header[]{emailTemplate};
        
        Test.startTest();
            

        Messaging.InboundEmailResult result = handler.handleInboundEmail(email, env);
        
        List<Notification__c> notifications = [
            SELECT Id, Date_Sent__c, FromUser__c, Notification_Text__c, Subject__c, Type__c,
            (SELECT Id, Notification__c, Recipient__c FROM NotificationRecipients__r) FROM Notification__c];
        
        System.assertEquals(1, notifications.size(), 'Inserted 1 Notification');

        Notification__c notification = notifications[0];

        System.assertEquals(1, notification.NotificationRecipients__r.size(), 'Inserted 1 User Notification');
        
        System.assertEquals(Date.today(), notification.Date_Sent__c, 'Date_Sent__c');
        System.assertEquals(fromUser.Id, notification.FromUser__c, 'FromUser__c');
		    System.assertEquals(email.plainTextBody, notification.Notification_Text__c, 'Notification_Text__c');
		    System.assertEquals(email.subject, notification.Subject__c, 'Subject__c');
		    System.assertEquals('Alert', notification.Type__c, 'Type__c');
        User_Notification__c userNotification = notification.NotificationRecipients__r[0];
        System.assertEquals(notification.id, userNotification.Notification__c, 'Notification__c');
        System.assertEquals(toUser.id, userNotification.Recipient__c, 'Recipient__c');
        
        Test.stopTest();
    }
}